### PR TITLE
update base image to jammy

### PR DESCRIPTION
**Pull request by nathanejohnson**
## Proposed change

```txt
This bumps the base image to ubuntu 22.04 "jammy".  This gets us to Transmission v3.0
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to a this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by nathanejohnson** [comment]
I'm running this image locally with PIA and so far so good.

**Comment by pkishino** [comment]
3.0 was already available before but we decided not to go with 3.0 due to other issues, see discussion

**Comment by nathanejohnson** [comment]
@pkishino from a quick search I haven't been able to find any discussion about it.  Sorry, I'm new here :)

**Comment by pkishino** [comment]
#1936

**Comment by nathanejohnson** [comment]
fair enough.  closing this issue.  thanks

**Pull request closed without merging**
