### PR TITLE
Added GooseVPN support

### LINKED ISSUE #738: Adding Goose to list of providers
Is someone able to add Goose (https://goosevpn.com) to the list of providers?
That would be great.

### LINKED ISSUE #1206: GooseVPN
**Which provider?**
GooseVPN

**Where are the configs?**

[Goose.zip](https://github.com/haugene/docker-transmission-openvpn/files/4676064/Goose.zip)

### PR DESCRIPTION
**Pull request by MartinHotmann**
resolves #738
resolves #1206

Added GooseVPN .ovpn files [2021.08.31] directly from GooseVPN support page.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (which adds functionality to a this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information
All GooseVPN POPs included are:

- au-7.ovpn
- be-1.ovpn
- be-15.ovpn
- be-16.ovpn
- be-17.ovpn
- bg-1.ovpn
- ca-4.ovpn
- ch-4.ovpn
- cz-2.ovpn
- de-10.ovpn
- de-11.ovpn
- de-12.ovpn
- de-13.ovpn
- de-14.ovpn
- dk-2.ovpn
- dk-3.ovpn
- es-4.ovpn
- fr-5.ovpn
- fr-6.ovpn
- fr-7.ovpn
- hu-2.ovpn
- in-1.ovpn
- it-5.ovpn
- it-6.ovpn
- jp-1.ovpn
- nl-23.ovpn
- nl-24.ovpn
- nl-25.ovpn
- nl-26.ovpn
- nl-27.ovpn
- nl-28.ovpn
- nl-41.ovpn
- nl-42.ovpn
- nl-43.ovpn
- nl-7.ovpn
- nl-8.ovpn
- no-1.ovpn
- pl-2.ovpn
- ro-10.ovpn
- se-5.ovpn
- sg-2.ovpn
- sg-3.ovpn
- uk-26.ovpn
- uk-33.ovpn
- uk-34.ovpn
- uk-35.ovpn
- uk-36.ovpn
- uk-7.ovpn
- us-33.ovpn
- us-34.ovpn
- us-35.ovpn
- us-36.ovpn
- us-41.ovpn

## Checklist
- [X] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by MartinHotmann** [comment]
If anything else is needed pls contact me.

**Comment by pkishino** [comment]
as the PR template mentioned, please put this PR on the config repo.. won't be adding any new configs to the repo here.
https://github.com/haugene/vpn-configs-contrib

**Comment by MartinHotmann** [comment]
> as the PR template mentioned, please put this PR on the config repo.. won't be adding any new configs to the repo here.
> https://github.com/haugene/vpn-configs-contrib

Thanks will do so.

**Comment by MartinHotmann** [comment]
@pkishino done, thanks!
https://github.com/haugene/vpn-configs-contrib/pull/36

**Pull request closed without merging**
