### PR TITLE
Fix DNS leak by updating /etc/resolve.conf

### PR DESCRIPTION
**Pull request by Xenov-X**
Add scripts to OpenVPN startup to update /etc/resolv.conf with VPN providers DNS servers, stopping DNS leakage. 

@clement-z already observed files to complete similar function are available in /etc/openvpn/. Visually they appear near identical (I haven't diff'd them), but both achieve the functionality desired.

This implementation uses:
/usr/share/openrc/support/openvpn/up.sh
/usr/share/openrc/support/openvpn/down.sh

However a valid alternative would be:
/etc/openvpn/up.sh
/etc/openvpn/down.sh

Only other point of note is setting DNS to correct values before transmission starts and after it closes.

Ref Issue #1455 
Prev pull req #1614 (cancelled because I can't manage my branches) (Sorry)

### CODE REVIEW

**Comment by pkishino** [comment]
this causes issues as seen here #1667

**Comment by clement-z** [comment]
I thought the down.sh was supposed to take care of this 🤔 

I am currently on mobile so I can't check but I will take a look.

**Comment by Xenov-X** [comment]
Seems like somehow they've stopped openvpn without down.sh running. 

May need to use --down-restart and --up-restart too to account for openvpn process being killed & it not running the down action

**Comment by clement-z** [comment]
So any news on that side ?

**Comment by ntalbo** [comment]
I seem to have fixed the DNS leaks by modifying my tunnelUp.sh, as per https://github.com/haugene/docker-transmission-openvpn/issues/558#issuecomment-596058869. It seems to allow the Mullvad server to properly push the DNS to resolv.conf. No issues while restarting the container and it seems to stay connected while running.

Not sure whether this is a proper fix, I sadly lack the technical know-how to fully understand the problem. I'd be glad to help troubleshooting if needed.

**Pull request merged**
