### PR TITLE
Fixed issue with default.ovpn stopping container from running

### LINKED ISSUE #752: Bug with NordVPN in latest release
Hi everyone-
  watchtower seemed to have updated transmission-vpn docker on my system last night.  Now I get the following log msgs over and over.  I tried searching around but came up short. Can anyone help?

> Using OpenVPN provider: NORDVPN
> 2019-03-25 13:16:01 Checking curl installation
> 2019-03-25 13:16:01 Checking unzip installation
> 2019-03-25 13:16:01 Removing existing configs
> 2019-03-25 13:16:01 Downloading latest configs
> 2019-03-25 13:16:01 Checking line endings
> 2019-03-25 13:16:01 Updating configs for docker-transmission-openvpn
> sed: can't read default.ovpn: No such file or directory

### PR DESCRIPTION
**Pull request by Troubadoure**
container was being stopped due to sed not liking default.ovpn symlink. Updated so that sed skipped this symlink. container was then also being stopped due to updateConfigs.sh script erroring if default.ovpn existed when trying to create symlink. Added option 'f' so that the symlink would be recreated even if existed. Also changed default of TCP to UDP in dockerfile for NordVPN

Fixes #752

### CODE REVIEW

**Comment by haugene** [comment]
Great, LGTM 👍 
Thanks for the fix

**Comment by Troubadoure** [comment]
No problem - cheers for merging 👍

**Comment by sameep22** [comment]
Hey guys, 

First of all, thanks for working so quickly to resolve this bug. I don't get the same error anymore, but I get this error in my logs :


Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/nl15.nordvpn.com.tcp.ovpn.ovpn:1: html (2.4.7)


Use --help for more information.

Can anyone help me?

**Comment by haugene** [comment]
@sameep22 Please post your docker run command. Are you setting OPENVPN_CONFIG?
Whole logs and the contents of that config file would also be helpful.

**Comment by sameep22** [comment]
@haugene , thanks for the reply.

I use docker-compose to mount my containers, and here is my command :
```
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "<PORT NO>:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - ${USERDIR}/Downloads:/data/watch
      - ${USERDIR}/Downloads/completed:/data/completed
      - ${USERDIR}/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=********@gmail.com
      - OPENVPN_PASSWORD=********
      - OPENVPN_CONFIG=nl15.nordvpn.com.tcp.ovpn
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.1.*,*.*.*.*"
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true

```
I have not edited the config file, and as for the logs, I use portainer to see them. Here is the logs :
```
2019-03-27 11:04:16 Best server : fr205.nordvpn.com,
2019-03-27 11:04:16 Downloading config: default.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0   6155      0 --:--:-- --:--:-- --:--:--  6160,
2019-03-27 11:04:16 Downloading config: nl15.nordvpn.com.tcp.ovpn.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    340      0 --:--:-- --:--:-- --:--:--   341,
2019-03-27 11:04:16 Checking line endings,
2019-03-27 11:04:16 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config nl15.nordvpn.com.tcp.ovpn.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/nl15.nordvpn.com.tcp.ovpn.ovpn:1: html (2.4.7),
Use --help for more information.,
Using OpenVPN provider: NORDVPN,
2019-03-27 11:05:24 Checking curl installation,
2019-03-27 11:05:24 Removing existing configs,
2019-03-27 11:05:24 Selecting the best server...,
2019-03-27 11:05:24 Searching for technology: openvpn_udp,
2019-03-27 11:05:24 Best server : fr205.nordvpn.com,
2019-03-27 11:05:24 Downloading config: default.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0   6982      0 --:--:-- --:--:-- --:--:--  6987,
2019-03-27 11:05:24 Downloading config: nl15.nordvpn.com.tcp.ovpn.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    357      0 --:--:-- --:--:-- --:--:--   358,
2019-03-27 11:05:24 Checking line endings,
2019-03-27 11:05:24 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config nl15.nordvpn.com.tcp.ovpn.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/nl15.nordvpn.com.tcp.ovpn.ovpn:1: html (2.4.7),
Use --help for more information.,
Using OpenVPN provider: NORDVPN,
2019-03-27 11:06:31 Checking curl installation,
2019-03-27 11:06:31 Removing existing configs,
2019-03-27 11:06:31 Selecting the best server...,
2019-03-27 11:06:31 Searching for technology: openvpn_udp,
2019-03-27 11:06:31 Best server : fr205.nordvpn.com,
2019-03-27 11:06:31 Downloading config: default.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0   6447      0 --:--:-- --:--:-- --:--:--  6457,
2019-03-27 11:06:31 Downloading config: nl15.nordvpn.com.tcp.ovpn.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    377      0 --:--:-- --:--:-- --:--:--   378,
2019-03-27 11:06:31 Checking line endings,
2019-03-27 11:06:31 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config nl15.nordvpn.com.tcp.ovpn.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/nl15.nordvpn.com.tcp.ovpn.ovpn:1: html (2.4.7),
Use --help for more information.,
Using OpenVPN provider: NORDVPN,
2019-03-27 11:07:39 Checking curl installation,
2019-03-27 11:07:39 Removing existing configs,
2019-03-27 11:07:39 Selecting the best server...,
2019-03-27 11:07:39 Searching for technology: openvpn_udp,
2019-03-27 11:07:39 Best server : fr205.nordvpn.com,
2019-03-27 11:07:39 Downloading config: default.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0   6282      0 --:--:-- --:--:-- --:--:--  6284,
2019-03-27 11:07:39 Downloading config: nl15.nordvpn.com.tcp.ovpn.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  3   162    3     6    0     0      6      0  0:00:27 --:--:--  0:00:27     6
100   162  100   162    0     0    182      0 --:--:-- --:--:-- --:--:--   182,
2019-03-27 11:07:39 Checking line endings,
2019-03-27 11:07:39 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config nl15.nordvpn.com.tcp.ovpn.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/nl15.nordvpn.com.tcp.ovpn.ovpn:1: html (2.4.7),
Use --help for more information.,
Using OpenVPN provider: NORDVPN,
2019-03-27 11:08:48 Checking curl installation,
2019-03-27 11:08:48 Removing existing configs,
2019-03-27 11:08:48 Selecting the best server...,
2019-03-27 11:08:48 Searching for technology: openvpn_udp,
2019-03-27 11:08:48 Best server : fr294.nordvpn.com,
2019-03-27 11:08:48 Downloading config: default.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0   5807      0 --:--:-- --:--:-- --:--:--  5815,
2019-03-27 11:08:48 Downloading config: nl15.nordvpn.com.tcp.ovpn.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    395      0 --:--:-- --:--:-- --:--:--   395,
2019-03-27 11:08:48 Checking line endings,
2019-03-27 11:08:48 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config nl15.nordvpn.com.tcp.ovpn.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/nl15.nordvpn.com.tcp.ovpn.ovpn:1: html (2.4.7),
Use --help for more information.,
```

**Comment by haugene** [comment]
.ovpn is automatically appended to the config name, so instead of:
`OPENVPN_CONFIG=nl15.nordvpn.com.tcp.ovpn`

Try instead:
`OPENVPN_CONFIG=nl15.nordvpn.com.tcp`

**Comment by sameep22** [comment]
I tried, unsuccessfully, removing the .ovpn, changing the server, and removing the parameter altogether. I still am facing the same issue. I have attached the log where I try to use another server.

```
2019-03-27 12:09:32 Best server : fr272.nordvpn.com,
2019-03-27 12:09:32 Downloading config: default.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0  10053      0 --:--:-- --:--:-- --:--:-- 10068,
2019-03-27 12:09:32 Downloading config: fr266.nordvpn.com.tcp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    582      0 --:--:-- --:--:-- --:--:--   584,
2019-03-27 12:09:32 Checking line endings,
2019-03-27 12:09:32 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config fr266.nordvpn.com.tcp.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/fr266.nordvpn.com.tcp.ovpn:1: html (2.4.7),
Use --help for more information.,
Using OpenVPN provider: NORDVPN,
2019-03-27 12:09:38 Checking curl installation,
2019-03-27 12:09:38 Removing existing configs,
2019-03-27 12:09:38 Selecting the best server...,
2019-03-27 12:09:38 Searching for technology: openvpn_udp,
2019-03-27 12:09:38 Best server : fr272.nordvpn.com,
2019-03-27 12:09:38 Downloading config: default.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0   9919      0 --:--:-- --:--:-- --:--:--  9960,
2019-03-27 12:09:38 Downloading config: fr266.nordvpn.com.tcp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    585      0 --:--:-- --:--:-- --:--:--   586,
2019-03-27 12:09:38 Checking line endings,
2019-03-27 12:09:38 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config fr266.nordvpn.com.tcp.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/fr266.nordvpn.com.tcp.ovpn:1: html (2.4.7),
Use --help for more information.,
Using OpenVPN provider: NORDVPN,
2019-03-27 12:09:44 Checking curl installation,
2019-03-27 12:09:44 Removing existing configs,
2019-03-27 12:09:44 Selecting the best server...,
2019-03-27 12:09:44 Searching for technology: openvpn_udp,
2019-03-27 12:09:44 Best server : fr272.nordvpn.com,
2019-03-27 12:09:44 Downloading config: default.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0   9014      0 --:--:-- --:--:-- --:--:--  9032,
2019-03-27 12:09:44 Downloading config: fr266.nordvpn.com.tcp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    581      0 --:--:-- --:--:-- --:--:--   580,
2019-03-27 12:09:44 Checking line endings,
2019-03-27 12:09:44 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config fr266.nordvpn.com.tcp.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/fr266.nordvpn.com.tcp.ovpn:1: html (2.4.7),
Use --help for more information.,
Using OpenVPN provider: NORDVPN,
2019-03-27 12:09:50 Checking curl installation,
2019-03-27 12:09:50 Removing existing configs,
2019-03-27 12:09:50 Selecting the best server...,
2019-03-27 12:09:50 Searching for technology: openvpn_udp,
2019-03-27 12:09:50 Best server : fr272.nordvpn.com,
2019-03-27 12:09:50 Downloading config: default.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0   9940      0 --:--:-- --:--:-- --:--:--  9925,
2019-03-27 12:09:50 Downloading config: fr266.nordvpn.com.tcp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    581      0 --:--:-- --:--:-- --:--:--   582,
2019-03-27 12:09:50 Checking line endings,
2019-03-27 12:09:50 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config fr266.nordvpn.com.tcp.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/fr266.nordvpn.com.tcp.ovpn:1: html (2.4.7),
Use --help for more information.,
Using OpenVPN provider: NORDVPN,
2019-03-27 12:09:58 Checking curl installation,
2019-03-27 12:09:58 Removing existing configs,
2019-03-27 12:09:58 Selecting the best server...,
2019-03-27 12:09:58 Searching for technology: openvpn_udp,
2019-03-27 12:09:58 Best server : fr272.nordvpn.com,
2019-03-27 12:09:58 Downloading config: default.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0  10250      0 --:--:-- --:--:-- --:--:-- 10289,
2019-03-27 12:09:58 Downloading config: fr266.nordvpn.com.tcp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    571      0 --:--:-- --:--:-- --:--:--   570,
2019-03-27 12:09:58 Checking line endings,
2019-03-27 12:09:58 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config fr266.nordvpn.com.tcp.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/fr266.nordvpn.com.tcp.ovpn:1: html (2.4.7),
Use --help for more information.,
```

**Comment by Troubadoure** [comment]
Found the issue - the NordVPN_CATEGORY isn't getting set correctly and as such it is trying to download the script form the udp location instead of tcp.

For the time being you can let it set the config for you automatically using NORDVPN_COUNTRY=nl instead of the OPENVPN_CONFIG parameter or use the udp config instead. 

Will update with a fix shortly

**Comment by sameep22** [comment]
Thanks @Troubadoure , I used the NORDVPN_COUNTRY parameter and it's working for now.

**Comment by Troubadoure** [comment]
Having just downloaded all of the latest config scripts from https://nordvpn.com/api/files/zip it looks like that server (nl15) doesn't exist anymore (at least not in terms of config scripts you may be able to connect to it with an old config script). Could you try with nl21.nordvpn.com.udp

You did identify another issue however fixed in pull request 760

**Comment by sameep22** [comment]
I did try using fr272 and fr266, however it didn't seem to make any difference. I have a few downloads lined up now, but I can try out nl21 in sometime.

**Comment by matthewjporter** [comment]
First off, great work

So, I had this issue and added the following in my config. The below config was located in my /etc/openvpn/nordvpn folder so used that
 
      - OPENVPN_CONFIG=uk737.nordvpn.com.udp

Now able to get past the default.ovpn missing error

**Pull request merged**
