### PR TITLE
Update docker base images

### LINKED ISSUE #936: Update tinyproxy version to include basic HTTP authentication
**Is your feature request related to a problem? Please describe.**
I want to use tinyproxy include [basic HTTP authentication](https://github.com/tinyproxy/tinyproxy/pull/129/files) which need to update tinyproxy to 1.10

I searched ubuntu package, tinyproxy 1.10 included in 18.10 and 19.04

https://packages.ubuntu.com/search?keywords=tinyproxy&searchon=names&suite=all&section=all

**Describe the solution you'd like**
The simple solution should be just upgrade the base image.

Also I don't see tinyproxy installed in alpine. [alpine 3.8 also doesn't have tinyproxy 1.10](https://pkgs.alpinelinux.org/packages?name=tinyproxy&branch=v3.8), change base image to 3.9 will include 1.10

### PR DESCRIPTION
**Pull request by jlnostr**
Updates:
- `ubuntu:16.04` -> `ubuntu:18.04`
- `alpine:3.8` -> `alpine:3.10`

This should also fix #936.

### CODE REVIEW

**Comment by jlnostr** [comment]
Checked the images, both include tinyproxy 1.10. Therefore the linked issue can be definitely closed with this PR.

**Comment by wilmardo** [comment]
@jlnostr Alpine can be bumped to 3.11 now

@haugene Can this be merged? Is see no issue in keeping up to date with the base images :)

**Comment by jlnostr** [comment]
@wilmardo Thanks for the tip. Nevertheless, I've accidentally deleted my fork some time ago. So unfortunately, I can't push another commit :D

**Comment by haugene** [comment]
Hey guys. I'm sorry there has been no activity on the repo from my side for a while. There's just been too much to do for a while. I'm searching for a couple of days to merge a lot of PRs and try to close some issues - but... Not so far.

I've seen this getting some bumps and the reason why I didn't merge it to begin with was that I tried to bump to ubuntu:18 at some point and it didn't start the way it was supposed to. I don't remember what failed exactly. Anyhow, you've probably tested this - so let's go. I'll merge to dev first so that we can test it before going to master branch.

If you could pull the dev tag and verify that it's working after the build that would be great. Will change alpine to 3.11 once merged.

**Comment by haugene** [comment]
And thanks for contributing @jlnostr! I'll try to be faster next time 🤞

**Comment by jlnostr** [comment]
Oops, missed to push a commit that fixes the build with the `ubuntu` image. The alpine image is working fine. Will publish a second PR asap!

**Pull request merged**
