### PR TITLE
feat(web-ui): add transmission-web-control UI

### PR DESCRIPTION
**Pull request by davinkevin**
This is based upon the project https://github.com/ronggang/transmission-web-control/

### CODE REVIEW

**Comment by haugene** [comment]
Hey. Changes looks good, looking forward to testing the new UI!
I changed the PR to the dev branch where the newest version is. There is a small conflict in the alpine dockerfile. Fix that and I'll merge it. Thanks!

**Comment by davinkevin** [comment]
Done 👍

**Comment by haugene** [comment]
Good stuff! Thanks for contributing :D

**Comment by h45rd** [comment]
That's a really cool GUI and your implementation is working nicely, @davinkevin.
Thanks for drawing my attention to it :+1: 

I would even go as far as to suggest making this webif the default.
What do you guys think?

Noticed one small hitch while giving it a quick testing. The _Original UI_ link 404s.
We should symlink or copy the index.html of the default transmission ui to index.original.html, see [the author's install script](https://github.com/ronggang/transmission-web-control/blob/fefe1768678bfc0ce53ced3f3694fc1464a4ac69/release/install-tr-control.sh#L89)

**Pull request merged**
