### PR TITLE
Added healthcheck for armhf systems

### PR DESCRIPTION
**Pull request by koenvanderlinden**
Adding the scripts/healthcheck.sh will make health check work on armhf based systems.

### CODE REVIEW

**Comment by haugene** [comment]
I agree, these should be included. So merging this now.

Another question is if the health checks should be activated from the Dockerfile as they are in the ubuntu based version. Ref: https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile#L137

Any thoughts? This could be added when starting the container, and in the inverse case they can be disabled for those who don't want them. Question is what the default should be.

**Comment by koenvanderlinden** [comment]
I don't know about the activation. I use this image in my Portainer docker controller and notices that it couldn't validate the health state. So adding this file fixed this.
I don't know if there are any side effects.

**Comment by sstassin** [comment]
Hi all.
I didn't see pullrequest... so i made a fork and add the HEALTHCHECK command in my "Dockerfile.armhf" file... just like it was done in the "Dockerfile".... and after several days of use... it is workink just like a charm (see screenshot) 
Transmission COntaine Fail
.
From my point of view, this command should always be present in the dockerfile itself because  : 
- what we want is always an up and running VPN connection
- associated to the docker run "RESTART ALWAYS" directive, we are sur to have an 98% uptime of our container.

**Comment by sstassin** [comment]
Do you want me to create a PR ?? because it is only a line

**Comment by sstassin** [comment]
> I don't know about the activation. I use this image in my Portainer docker controller and notices that it couldn't validate the health state. So adding this file fixed this.
> I don't know if there are any side effects.

Yes you are right... in fact the HEALTHCHECK command is not used by the Docker Engine... so i do not see inside the "docker logs" command any echo output displayed by the healthcheck.sh command..

So the container is always we the state "Healthy" and is never restarted by the Docker Engine !!
Is it really working on the non-armf images ??? Do you know what could happen wrong here

Regards

**Comment by sstassin** [comment]
Hi.
Just to add some more information...

```
pi@rpi3bplus:~ $ docker exec  transmission /bin/bash /etc/scripts/healthcheck.sh
PING google.com (216.58.207.206) 56(84) bytes of data.
64 bytes from arn11s04-in-f14.1e100.net (216.58.207.206): icmp_seq=1 ttl=55 time=81.5 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 81.501/81.501/81.501/0.000 ms
Network is up
pi@rpi3bplus:~ $ echo $?

```
The Command is returning a valid exit code

**Pull request merged**
