### PR TITLE
Fix rss build

### PR DESCRIPTION
**Pull request by ilike2burnthing**
## Breaking change

```txt
none
```

## Proposed change

```txt
Fix RSS build, based on https://github.com/ffi/ffi/issues/1103
```

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by pkishino** [comment]
Hey, thanks a lot for these efforts!

**Comment by ilike2burnthing** [comment]
No worries. Looks like that resolved the issue on dev branch, so I'll leave you to decide if you wanna do the same on master, or merge dev into master and then master into dev to balance them out (I don't think there's anything left in dev that's still being tested).

**Comment by ilike2burnthing** [comment]
I tell a lie, we'd need to check that the auto-build works fine - https://github.com/haugene/docker-transmission-openvpn/pull/2860. We weren't able to test this fully because of the RSS build issue.

**Comment by ilike2burnthing** [comment]
Looks like #2861 worked! I'll leave the rest of https://github.com/haugene/docker-transmission-openvpn/pull/2859#issuecomment-2191690522 to you!

**Pull request merged**
