### PR TITLE
Some spelling and grammar fixes

### PR DESCRIPTION
**Pull request by Moohan**
## Breaking change

```txt
<placeholder>
```

## Proposed change

```txt
<placeholder>
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to a this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Why did these need to be 6 separate PRs?

**Comment by Moohan** [comment]
They didn't... I spotted a mistake so I fixed it then got carried away. In hindsight, I could have added extra commits to the same branch / PR.

**Comment by ilike2burnthing** [comment]
You still can, and then just close the other 5.

**Comment by Moohan** [comment]
Closed as all changes now on #2119

**Pull request closed without merging**
