### PR TITLE
Updated PureVPN configuration files

### PR DESCRIPTION
**Pull request by Othou**
Old configuration files has been moved to "old configs" folder

### CODE REVIEW

**Comment by haugene** [comment]
Great! But do we want to keep the old configs? Are they still working, and will they be obsolete soon?
If we are to keep the old ones, please rename the folder to "old" as spaces in the path requires escaping the whitespace char etc.

Also. If we're keeping the old configs, they need to be changed so that they point to the old ca.crt as well. As far as I can see they're pointing to the main ca now.

**Comment by merlinfrombelgium** [comment]
Great stuff @othou. I did find an error in the config file for Netherlands-udp: it has the FQDN for Norway. Please correct it to the correct name before committing. Looking forward to having a stable config thanks to your work!

**Comment by haugene** [comment]
Thoughs on the old configs @merlinfrombelgium? Should we keep them in /old/ or just clean it out? Seems to me as there are enough options among the new servers IMHO. But I don't use this provider, so I don't have any strong feeling either way. Just that it will be cleaner ;)

**Comment by Othou** [comment]
Don't mention it, I'm happy that I can contribute somehow for this awesome container :) I will get into this later today after work, maybe add some more servers I have

**Comment by haugene** [comment]
Oh, and btw. See #590. We should rename configs with comma in the name, to avoid it being treated as a list of configs. If you those with comma to use - instead, then that bug will be corrected as well :)

**Comment by Othou** [comment]
Alright. I removed old configs, fixed Netherlands-udp and added all other servers i got from PureVPN support. All done for now :)

**Comment by haugene** [comment]
Cool! Looks good to me. Merging to dev so that people can test it.

**Comment by rrd911** [comment]
I noticed in dev there are fewer gateways. are more being added?

**Comment by Othou** [comment]
@rrd911 I added all gateways i got from PureVPN Support. If i understood correctly, they are in progress of making new gateways, so there might be more gateways later for this container.

**Comment by rrd911** [comment]
There are more configurations for PureVPN based on the server page.

https://support.purevpn.com/vpn-servers

**Pull request merged**
