### PR TITLE
Add Transmissionic Web UI & New Documentation

### PR DESCRIPTION
**Pull request by apsoyka**
## Proposed change

This PR packages the open-source web UI [Transmissionic](https://github.com/6c65726f79/Transmissionic) as part of the Docker image. The Transmissionic project has 233 stars on GitHub at the time of writing, has received a commit in the last 30 days and describes itself as follows:

> Transmissionic is a free multi-platform remote for Transmission Daemon built with [Ionic](https://ionicframework.com/) and [Vue.js](https://vuejs.org/).
> It can be used as [Web Interface](https://github.com/transmission/transmission/wiki/Web-Interface), Android/iOS app and Windows/Linux/macOS program.

This project already includes several choices for web UIs. I feel that this particular web UI ought to be included as part of the official Docker image for the following reasons:

- It has a polished user experience and is mobile-friendly with a responsive layout.
- Based on my own testing, it seems to be compatible with the recent Transmission 4.0.2 release.
- The project is actively maintained.

Note: I am not associated with the Transmissionic project or it's maintainers in any way.

## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information
- Link to documentation updated (if done separately): ```https://haugene.github.io/docker-transmission-openvpn/config-options```

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated

### CODE REVIEW

**Comment by pkishino** [comment]
cheers, will add to dev for now

**Comment by ilike2burnthing** [comment]
Is there a way to change to dark mode in the UI that I'm missing, or is it just limited to the [default.json method](https://github.com/6c65726f79/Transmissionic#default-settings)?

**Comment by apsoyka** [comment]
@ilike2burnthing

Yes, you can switch between the dark, light & system default theme using the settings menu on the right.

**Comment by ilike2burnthing** [comment]
Ok, I must have missed it then :/ brb

**Comment by ilike2burnthing** [comment]
Nope :/ and Preferences is just for Transmission.

**Comment by pkishino** [comment]
Browser caching?

**Comment by apsoyka** [comment]
@ilike2burnthing

That looks like the default Transmission web UI. It's likely that you aren't using the right web UI. Please try disabling caching in your browser dev tools.

**Comment by ilike2burnthing** [comment]
Yep, that's the default UI. I've been using the Flood UI since it was added, didn't recognise the new 4.0 UI.

Oh ffs, I've just realised the issue, despite @pkishino having posted it about it at the time. The latest dev build didn't publish for some reason, so no wonder it's not working.

@pkishino did you try rerunning the build workflow, in case it was a temporary Actions issue?

**Comment by pkishino** [comment]
Yeah.. a few times.. it’s something strange regarding dependencies that
doesn’t show on local build

**Comment by haugene** [comment]
It's building `linux/amd64, linux/arm/v7 and linux/arm64` in parallel with buildx. And it looks to me like the last failure was coming from `linux/arm64`. Now that might be random, but it could also mean that it builds fine locally as amd64 but that there is some cross-platform build stuff that's breaking. And those are usually not fun to debug :see_no_evil:

**Comment by ilike2burnthing** [comment]
Well https://github.com/haugene/docker-transmission-openvpn/commit/30d070dce5b7ab021eaf64a310594e939eaac779 built successfully 🤷

Got to play around with Transmissionic. Looks really nice, but think I prefer Flood still (though that may be familiarity over anything else).

**Pull request merged**
