### PR TITLE
Use the build release version from Flood instead of building ourselves

### PR DESCRIPTION
**Pull request by johman10**
I noticed that the building process was really not that great, so I started to automatically create releases.

To help you out I'm here to update your code to use those releases. This should improve your build speed quite significantly. :)

Hope this helps you!

**Please note that I may need some help testing this. I didn't find any instructions on how to test this locally so I'm pushing hoping for some CI to kick in. :)**

### CODE REVIEW

**Comment by johman10** [comment]
Just wanted to note that this basically resolves the comment from here: https://github.com/haugene/docker-transmission-openvpn/pull/1663#issuecomment-780911645.

**Comment by pkishino** [comment]
can you please rebase this and and unlink it from the previous commits? also, I changed it to dev repo for initial commit, then if everything fine I'll create another PR to merge into master

**Review by pkishino — APPROVED** [review]

**Comment by johman10** [comment]
@pkishino should be good to go now! :)

**Comment by haugene** [comment]
Thanks a lot @johman10. That brings the build time back down to 2 minutes :clap: :pray: 

I saw the discussion in #1661 mentioning that flood has support for Transmission, but still you have another project that is called flood-for-transmission. I see they refer to it as a fork but as I understand it it is not a fork but a separate project using the same layout and graphical components.

What are your thoughts on this? Did you make yours while flood did not have Transmission support and now it does? Do you still intend to continue development on your project? I'm not very familiar with either project (even if I'm running your UI now and like it a lot :smile:) and thought you might be the best source of insight here.

**Comment by johman10** [comment]
@haugene thanks a lot for reaching out to me in this way.

Basically around the summer of 2020 I started this "Flood for Transmission" project to make Flood, which only supported rtorrent, but yet a great looking UI, work together with Transmission. At that time I didn't talk to anyone about it, nor did I push my code anywhere. And as far as my knowledge reaches no other project was aiming to do this.

After I felt confident enough about my progress (which for me basically meant feature complete :sweat_smile:) I decided it was time to bring it out into the world, this was around last Christmas. This is when I noticed that Jesec has actually been working on this fork of the main repo, and that it supported Transmission in a beta stage. I reached out to him and he wasn't entirely against us both having our repository up.

To me there is quite a distinct difference between our two projects. The Flood fork from Jesec is basically it's own service that you have to run, it runs it's own backend and so takes up resources from the system. My project is purely a frontend client using the RPC API from Transmission and while depending on the Transmission server to serve the files.

All this said, Jesec does a great job and he seems super productive on his project. I think it's a great alternative if you have resources available, but if you want a small footprint and a dedicated Transmission client my project is a good alternative.

I will definitely keep maintaining this project as long as I deem it fun and worth my while. I consider you guys adding my project to your images definitely a motivation.

If you, or anyone else reading this, have any feedback or feature requests please do create an issue on my repo and I will consider it.

**Comment by haugene** [comment]
Thanks for the summary @johman10. Sounds much like the journey of this project as well :smile: 

I think it's a really cool UI :clap: I hope you continue to develop it and I'm glad that this project could serve as a booster. As for supporting jesec/flood in the future, I would welcome that as well but I will not spend any time on it. It would have to come from the community I think, and then we could consider a PR. As all our current UIs are served by Transmission like yours it would be up to the contributor to find a good solution for how to handle the backend server it requires.

But I do want to do one change about the naming. Want to hear your thoughts on it. I don't really know what the difference between [Flood-UI/flood](https://github.com/Flood-UI/flood) and [jesec/flood](https://github.com/jesec/flood) but I see that the former links to the latter in the "About" section. So I guess they are the same project.

If that is "flood" and your project is "flood-for-transmission" I think that [this block](https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/start.sh#L44-L47) should maybe also check for `flood-for-transmission`:
```
if [[ "flood" = "$TRANSMISSION_WEB_UI" ]]; then
  echo "Using Flood for Transmission UI, overriding TRANSMISSION_WEB_HOME"
  export TRANSMISSION_WEB_HOME=/opt/transmission-ui/flood-for-transmission
fi
```

If anyone comes along and implements jesec/flood I think it should be called flood. And also to avoid questions about "this is not the flood I thought I was going to get" etc. What do you think?

As people have already started using it I would suggest printing an error message when "flood" is set, telling them to use "flood-for-transmission". That message could stay there for a while, as long as "flood" will not be implemented. What do you thing? Makes sense?

**Comment by johman10** [comment]
@haugene I'm definitely not against that change, and I almost made that change part of this PR when I realized that it would break for those that already use it today.

I can definitely help out with this PR as long as you're not in a hurry. My week is quite busy, but I can create some time during this weekend to look at it and implement the renaming as you are suggesting. Otherwise feel free to pick it up yourself. ;)

Just as an FYI: Flood-UI/flood is the original repo, which Jesec took over and added to his account instead. So the Flood-UI repo is basically deprecated.

**Comment by haugene** [comment]
We have a plan then. I pushed some changes now and created #1776. I suggest to merge that to master and it will become a part of 3.7 release and stay that way for the rest of 3.x.

We're moving towards 4.0 soon though, with extracted config repo. It is now in the dev branch and we probably just want to get feedback from some users before merging it. On the dev branch I will remove the `export TRANSMISSION_WEB_HOME=/opt/transmission-ui/flood-for-transmission` that makes this backwards compatible and change the warning logging to an error instead. But I'll keep the entry that checks for "flood" for a while so that anyone who have already started using it will see it in their logs when they see that the new UI is gone.

Sounds good?

**Pull request merged**
