### PR TITLE
Fix DNS leak by updating /etc/resolve.conf Fix for issue #1455

### PR DESCRIPTION
**Pull request by Xenov-X**
Uses OpenVPN scripts to update Resolv.conf at VPN start with DNS entries provided by OpenVPN server - only changes are to trigger the scripts to be run.

Ensures all DNS queries are routed via VPN provider, obscuring from ISPs

Issue ref  #1455

### CODE REVIEW

**Comment by clement-z** [comment]
It seems there also is a `up.sh` and `down.sh` in `/etc/openvpn/` (from the distro as far as I know ?).

The files are different. Why use one over the other? A quick check showed me both work (using PIA) for setting it up; I didn't try stopping openvpn and checking.

**Comment by clement-z** [comment]
Hmm @Xenov-X I think this is not what you meant to do ?

**Comment by Xenov-X** [comment]
ahhhhhh - you're right - the extra changes were not intended - lost track of what branch I was on.

ultimately, from what I can see, there seems no difference in functionality between the two  - both achieve updating /etc/resolv.conf with the VPN providers DNS entries.

Will work out how I can remove these changes...

**Comment by Xenov-X** [comment]
Going to close this Pull req - re fork and resubmit. It's a bit of a bombsite, I can't really work out whats rolled back.

**Comment by clement-z** [comment]
Yes I think it's the easiest solution 😃

**Pull request closed without merging**
