### PR TITLE
switch to github actions for mkdocs deploy

### PR DESCRIPTION
**Pull request by ksurl**
## Breaking change

```txt
no longer using circle ci to deploy mkdocs site
```

## Proposed change

```txt
use github actions to deploy mkdocs site
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this container)
- [x] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

In light of recent Circle CI security incident, maybe it's a good chance to fully switch over all CI workflows.

### CODE REVIEW

**Comment by ksurl** [comment]
it also may be a good idea to revoke existing tokens/secrets for circle ci to access this repo since those were part of the data leak.

**Comment by pkishino** [comment]
Looks good to me, tagged @haugene

**Comment by ilike2burnthing** [comment]
CircleCI shields.io links need to be removed from README.md and docs/index.md

CircleCI pipeline needs to be removed/disabled/deactivated/unlinked/whatever - https://app.circleci.com/pipelines/github/haugene/docker-transmission-openvpn/935

Build failing - https://github.com/haugene/docker-transmission-openvpn/actions/runs/3971962531/jobs/6809628027

```text
INFO     -  Copying '/home/runner/work/docker-transmission-openvpn/docker-transmission-openvpn/site' to 'gh-pages' branch and pushing to GitHub.
To https://github.com/haugene/docker-transmission-openvpn
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/haugene/docker-transmission-openvpn'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by haugene** [comment]
Excellent :clap: Thank you guys :pray: 

I have stopped the CircleCI project now :heavy_check_mark:

**Pull request merged**
