### PR TITLE
added a full list of SlickVPN configs (second attempt)

### PR DESCRIPTION
**Pull request by qoobaa**

### CODE REVIEW

**Comment by qoobaa** [comment]
How about now?

**Comment by haugene** [comment]
Looks good to me. Thanks for the effort of combining this, and contributing with a PR 👍 
@h45rd, any thoughts?

**Comment by h45rd** [comment]
Great work! Thank you :)

SlickVPN seems to be altering the gateway specific config files on their website rather frequently. E.g. exchanging one gateway (gwX.location.slickvpn.com -> gwY.location.slickvpn.com) for another, while both are still available, only providing one of many gateways per file, etc.
Not sure why they do this. Maybe semi-automated load-balancing or traffic steering for their proprietary application?

Wondering if we should create "universal" configs in the form of gw[1-4].location[1-3] port [443,8888] or if this could have detrimental effects on their servers when used by a wider user base.
Thoughts?

As I mentioned I have been using these kind of configs for a while without any obvious problems.
The main benefit being that usually every location has at least one gateway available, even if not currently listed on the official website.

**Comment by qoobaa** [comment]
I've just begun using SlickVPN, so I'm definitely not able to tell which approach is the best one. I tried the previous "Netherlands" config without any luck, so I decided to create this PR. I can prepare "universal" configs if you want me to - I like the idea, we could test it.

**Comment by haugene** [comment]
Should I merge this now, or do you want to try the universal approach?

If you want to test different stuff I can try to be quick accepting your PRs in the future - then SlickVPN is your wheelhouse :)

**Comment by qoobaa** [comment]
Done.

**Comment by h45rd** [comment]
Man.. you are quick :+1: 

These are the variations I use:
```
remote gw1.${gw}1.slickvpn.com 8888 udp
remote gw1.${gw}2.slickvpn.com 8888 udp
remote gw1.${gw}3.slickvpn.com 8888 udp
remote gw1.${gw}1.slickvpn.com 443 udp
remote gw1.${gw}2.slickvpn.com 443 udp
remote gw1.${gw}3.slickvpn.com 443 udp

remote gw2.${gw}1.slickvpn.com 8888 udp
remote gw2.${gw}2.slickvpn.com 8888 udp
remote gw2.${gw}3.slickvpn.com 8888 udp
remote gw2.${gw}1.slickvpn.com 443 udp
remote gw2.${gw}2.slickvpn.com 443 udp
remote gw2.${gw}3.slickvpn.com 443 udp

remote gw3.${gw}1.slickvpn.com 8888 udp
remote gw3.${gw}2.slickvpn.com 8888 udp
remote gw3.${gw}3.slickvpn.com 8888 udp
remote gw3.${gw}1.slickvpn.com 443 udp
remote gw3.${gw}2.slickvpn.com 443 udp
remote gw3.${gw}3.slickvpn.com 443 udp

remote gw4.${gw}1.slickvpn.com 8888 udp
remote gw4.${gw}2.slickvpn.com 8888 udp
remote gw4.${gw}3.slickvpn.com 8888 udp
remote gw4.${gw}1.slickvpn.com 443 udp
remote gw4.${gw}2.slickvpn.com 443 udp
remote gw4.${gw}3.slickvpn.com 443 udp
```

Going to do some testing on the weekend to see what gateways are actually available and which iterations make sense. Might do a pull request if I find something useful.
Github is great :)

**Pull request merged**
