### PR TITLE
ProtonVPN - Update OVPN configurations for p2p servers and remove non-p2p servers

### PR DESCRIPTION
**Pull request by jaygun**
Following changes have been made in this pull request:

- Update OVPN configurations for Iceland and Sweden p2p servers (resolves connectivity issues to these servers).
- Remove all OVPN configurations for non-p2p servers (p2p traffic on non-p2p servers are not permitted - See [https://protonvpn.com/support/p2p-vpn-redirection/](https://protonvpn.com/support/p2p-vpn-redirection/) for more information).

### CODE REVIEW

**Comment by haugene** [comment]
Hi, sorry about the delay here. I'm nudging this to scare off the stale bot for a little while more. 
Does this mean that ProtonVPN is not working anymore, or is it more of a cleanup and update of selected servers?

I had a look at their server overview and came across this: https://github.com/ProtonVPN/linux-cli
Would that be a tool that we could implement here? I think we would have to modify it slightly though.

**Comment by jaygun** [comment]
@haugene It is both clean up and fixes. Summary below:

>https://github.com/haugene/docker-transmission-openvpn/pull/1358/commits/f75ccfcb89baf472a1fabebf283fe3515bf6be60 - ProtonVPN has changed some server IPs/ports, thus breaking connectivity to these servers. This commit restores connectivity to these servers. As of today (2020-Nov-15), these updated configs in the commit are still valid.
>
>https://github.com/haugene/docker-transmission-openvpn/pull/1358/commits/954610854e466a270953723e209b7bbb0ca6cee6 - Currently, OPVN configuration files exist for *all* ProtonVPN servers, however only handful accept and are allowed P2P traffic. This commit removes all non-P2P server OVPN configs (which should not be used anyway for P2P). This should slim the ProtonVPN configs down quite a bit until we have a better solution for managing OVPN configs.
>
>https://github.com/haugene/docker-transmission-openvpn/pull/1358/commits/6fc254342e39849d4157051fe0c41e1ddf675422 - Removed another non-P2P, server as per above.

I am not too familiar with the ProtonVPN CLI; however it does look promising as OPVN configs do not appear to need to be maintained. I am all for simplifying the maintenance of the OVPN configs.

**Comment by haugene** [comment]
Thanks a lot @jaygun! One comment though. I'm going to wait for a few days to merge this, and hopefully be able to merge it in here instead: https://github.com/haugene/vpn-configs
ProtonVPN brings such an immense amount of files. Don't want to add 1500 more to the git repo if I can help it. Going to put some more effort into https://github.com/haugene/docker-transmission-openvpn/issues/1489 and get it done.

Hold on for now. I might have to rebase the other repo so don't create a PR there just yet :smile:

**Comment by jaygun** [comment]
@haugene - Completely understand. Just a note that after this commit, there will be only 136 files for ProtonVPN configs rather than 1500+

**Comment by haugene** [comment]
Oh. I was too quick. I saw 1500 files changed and forgot the math :laughing: 
Then it's worth it. Giving me some breathing room for #1489 as well ;)
I think I'll briefly merge it to the dev branch before going to latest. But I'll tag a new version on master today anyways I think so I'll push it out.

Thanks again for helping out :raised_hands:

**Pull request merged**
