### PR TITLE
Added support for 'watch-dir-force-generic'

### PR DESCRIPTION
**Pull request by aseber**
This pull request adds support for the transmission settings.json variable 'watch-dir-force-generic' discussed in this [transmissionbt article](https://forum.transmissionbt.com/viewtopic.php?t=17960).

This feature was discussed in Issue [#512](https://github.com/haugene/docker-transmission-openvpn/issues/512).

### CODE REVIEW

**Comment by haugene** [comment]
Merged 😄
Will be available on the dev tag very soon. Great if someone can test that it behaves as expected.

Thanks for contributing!

**Comment by aseber** [comment]
@haugene I've just confirmed that this feature works in the latest build of haugene/transmission-openvpn.

**Comment by haugene** [comment]
@aseber Great! 😄 I'll close the related issue then

**Comment by Spass1966** [comment]
This doesn't work for me. No amount  of environment variables get Transmission to recognize torrents in the folder.

```
 transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "5143:5143"
      - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/services/homes/{user}/seeding/complete:/data/completed
      - /var/services/homes/{user}/torrents:/data/watch
    environment:
      - PUID=0
      - PGID=101
      - TZ=Europe/Warsaw
      - OPENVPN_PROVIDER=Windscribe
      - OPENVPN_CONFIG=Poland-udp
      - OPENVPN_USERNAME={user}
      - OPENVPN_PASSWORD={password}
      - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/completed
      - TRANSMISSION_WATCH_DIR=/data/watch
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/24
```

**Comment by haugene** [comment]
@Spass1966 I see. And you've pulled the latest version of the image?

If you exec into the container and have a look at `/data/transmission-home/settings.json`, does it look OK? The property is set there as expected?

If so this is either a bug with Transmission not actually checking the folder every 10 seconds as it should or there's something with the volume.

Could you also try to not mount any volumes. Just start it without any mounts and then do a `docker cp some.torrent <container-name>:/data/watch/some.torrent` and see what happens then.

**Comment by Spass1966** [comment]
@haugene `settings.json` looks good to me:

```
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "10.110.190.34",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/data/completed",
    "download-limit": 100,
    "download-limit-enabled": 0,
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/data/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "max-peers-global": 200,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": false,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "{dd771a272d2805f292226001a6d1917d9b2243cayScu7DRg",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "username",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 2,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true,
    "watch-dir": "/data/watch",
    "watch-dir-enabled": true,
    "watch-dir-force-generic": true
}
```

I removed the mounts, restarted the container and invoked
`docker cp debian-9.8.0-amd64-netinst.iso.torrent transmission-openvpn:/data/watch/`. It was picked up right away and is downloading now.

Permissions on my folder mounts are {username}:users, which should be permissive enough for the root permissions I'm giving the container?

**Comment by haugene** [comment]
Hmm. Maybe this is about permissions then. The UID/GID you are using will be set to the transmission user in the container. I would set it to be the same UID/GID as your user is on the host. This is used to avoid running as root. If you remove UID/GID altogether then it will be root.

Using it to set UID to 0 is not intended. Does it complain about that in the logs?
Try setting regular UID/GID from your host user, and maybe create a couple of new (fresh) folders with normal permissions to test with. Or make sure that the directories you mount have the right ownership, group and chmod permissions.

**Comment by Spass1966** [comment]
Ok this is *very* strange. I did as you suggested and started moving files around, making new folders, `rsync-ing` things around to inherit new permissions etc etc. The Debian torrent always restarted. I looked more closely and all my other torrents had a filesize of 0. So somehow these torrents were corrupted or turned into useless placeholder files.

Thanks for helping me to debug this.

**Comment by haugene** [comment]
You're welcome 😄 Post back if you figure it out

**Comment by Spass1966** [comment]
Was able to re-download all my 0-byte torrents from their sources. Transmission picked them up right away. All is well with the world. :-)

**Pull request merged**
