### PR TITLE
Syntax clean up

### PR DESCRIPTION
**Pull request by jsloan117**
Simple and small changes. To try and clean up a little more of the start.sh code.
* Removed useless cat from L75
* FREEVPN_DOMAIN unused removed it -- Did a search and could not find this being used anywhere

### CODE REVIEW

**Comment by haugene** [comment]
Hey @jsloan117 and thanks a lot for wanting to help out keep the scripts clean.
As warned in the README I'm currently doing a larger refactor/restructuring of the scripts on the dev branch.

If you want to contribute there, that's great. Changing the PR towards dev, and then you probably have to rebase and fix some merge conflicts. I'll take another look when it's towards the "right" branch.

**Comment by jsloan117** [comment]
lol I guess I don't know git well enough to fix these issues. I think it'd be easier least for my time to just cancel this PR and I can re-review the code from your dev branch and see where my changes would apply if they still do.

**Comment by jsloan117** [comment]
Well I'm going to try and figure this out to make it right if thats fine if not we can close I'm sure if I don't have time.

**Comment by jsloan117** [comment]
Ok yeah I don't know how to fix this if its even possible. But I created a new branch on my end that is based from your dev branch called dev_syntax_cleanup if you can change my to that branch? I don't think its possible which is fine, we can just close this and I can create a new one.

**Comment by haugene** [comment]
Hey @jsloan117. Sorry about the very late response here. But I understand. Git can suddenly get very complicated when rebasing, especially when there are structural changes as well. I found your fix on the branch you mentioned and created #1395 to merge it into the project. I'm closing this PR and merging the other one :+1:

**Pull request closed without merging**
