### PR TITLE
Remove legacy options and update defaults

### PR DESCRIPTION
**Pull request by ilike2burnthing**
https://github.com/transmission/transmission/wiki/Editing-Configuration-Files

Deprecated in 1.5x and 1.4x

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
_There are some other differences between Transmission's default settings and those here. I haven't added them to this PR, as there's probably a good reason for most if not all of them. Hopefully someone can shed some light for those comments in bold._

### Missing
`lazy-bitfield-enabled: true` - should really be a default of 'false' anyway, if it even works


### Extra
`watch-dir-force-generic:` - from what I can tell, this does still exist, it's just not documented


### Different
*`incomplete-dir-enabled: false` - **why is the default 'true' used here?**

*`peer-limit-global: 240` - not much of a difference between that and '200'. **Update?**
*`peer-limit-per-torrent: 60` - same as above for '50'. **Update?**

*`peer-port-random-low: 1024` - '49152' makes more sense anyway
*`port-forwarding-enabled: true` - **why is the default 'false' used here?**

*`prefetch-enabled: true` - **set to '1' only in DockerEnv**

*`ratio-limit: 2.0` - python issue #1499

`rpc-host-whitelist-enabled: true` - **set to 'false' only in default-settings.json** - #432
*`rpc-whitelist: 127.0.0.1` - **set to '127.0.0.1,::1' only in default-settings.json**
*`rpc-whitelist-enabled: true` - explained in  #432 

*`umask: 18` - **why is the default '2' used here?**

`utp-enabled: true` - really should be a default of 'false' anyway #978

*= value unchanged from initial commit - https://github.com/haugene/docker-transmission-openvpn/commit/4eaaae0ec12cd2bad021190dcc10895c356f0f92

**Comment by haugene** [comment]
Thanks for taking a look at this! :+1:

I'll comment on what I remember/think to be true.

1. incomplete-dir-enabled: I think that's just me, from the old days. We built it to have a setup that we thought to be the "optimal one". And the container was dumber back then. Could be just because there are scripts that ensure that the folder exists etc. I have no problem with it being reverted to false - as long as we update the userSetup.sh scripts and others that modify permissions etc
2. peer-limit*: Agree that they should be changed to Transmission's default settings.
3. prefetch-enabled... Are we only having weird values in DockerEnv? The dafault is correct other than that?
4. The ratio is unfortunate because of the bug. We should maybe add a list to the python script on what variables can be double.
5. rpc-whitelist stuff. I guess this has to do with all clients being on other hosts than the container.
6. umask: :shrug: 
7. utp-enabled: Ah. So I re-introduced that one. Good catch, thanks. Should be false :+1: 
8. watch-dir-force-generic: yes, not very documented but I did find some reference to it when I looked once. It's for the systems that cant use inotify to detect new files in watch dir.

While we're on it. When I saw the DockerEnv file I got the urge to delete it. Thoughts?

**Comment by ilike2burnthing** [comment]
Sorry, I was typing all that at 4am. Reading it back now, it really seems like I was saying that settings with default values different to those from Transmission are somehow _**wrong**_. Really not what I was going for, was mostly just curious.

1. Given that many people use this along side Sonarr, Radarr, *arr, I think a default of true makes sense; separate incomplete and complete download folders to avoid any issues and make logs clearer. So I'd say keep it as true.
2. Any preference for whether I make a separate PR or just add them to this one?
3. Yea, in default-settings.json it is `"prefetch-enabled": true,`, whereas in DockerEnv it is `#TRANSMISSION_PREFETCH_ENABLED=1`, though it may be that both can be used but isn't documented (just a guess).
4. Outside of my skillset I'm afraid, so I'll leave that one to you (not like you have enough to work on or anything). 😉 
5. I suppose my concern there is the default in DockerEnv is `#TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=true`, so could that potentially cause issues?
6. Lets just smile and nod. 😋 
7. Apologies for the confusion, the listed settings above (e.g. `utp-enabled: true`) are the defaults provided by Transmission. So don't worry, it's still false here, that issue hasn't been reintroduced.
8. Makes sense!

As for DockerEnv, I have no strong opinions either way:
**+ve:** it's a a good reference for users to have, so they know the out-of-the-box settings
**-ve:** double the upkeep for changes

**Comment by haugene** [comment]
I see. It wasn't 4 am here when I responded, but it seems I've gotten it the wrong way around a couple of times as well :laughing: 
Anyways. I think I'll opt for deleting DockerEnv and try to put the upkeep effort into the docs instead. That solves number 3. and 5. here as well. For the rest:

1. :+1: We keep it
2. Same for me, just push everything in here if you want.
3. N/A :point_up: 
4. Hah. Getting there :crossed_fingers: :smile: 
5. N/A :point_up: 
6. Yes... These guys seem to know what they're doing though #1518. Might have a preference here.
7. Then we'll keep it :+1: 
8. :+1: 

Sounds like we have a plan :clap:

**Comment by ilike2burnthing** [comment]
Ready to go! Thanks for the insight

**Comment by clement-z** [comment]
I think keeping in sync with transmission's defaults is good. I wonder whether it's necessary with `umask` though, as IMO `002` is a relatively sane default for this container's intents.

Changing back `umask` to the default might be unexpected on some systems where group write permission is assumed on torrents. For example, if `sonarr` runs as `sonarr:mygroup`, `transmission` as `transmission:mygroup`, and `sonarr` is set to delete completed torrents after copying, it will result in (non-critical) errors.

So I think the best option is either leaving `umask` as-is or re-aligning it with transmission's default in the next major release.

**Comment by haugene** [comment]
Great stuff. Thanks for the update @ilike2burnthing :+1:

**Pull request merged**
