### PR TITLE
doc: Add docker secret as option for OpenVPN credentials in FAQ

### PR DESCRIPTION
**Pull request by leewc**
## Breaking change

```txt
<none>
```

## Proposed change

```txt
Adds documentation that docker secrets are supported in the container
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] FAQ Doc update/addition

## Additional information

- I looked at the code and realized it was supported, not sure if we want to link it in case the naming changes in future: https://github.com/haugene/docker-transmission-openvpn/blob/HEAD/openvpn/start.sh#L200

## Checklist

- [ ] The code change is tested and works locally.
- [X] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [X] Documentation added/updated

PS: Thank you for this! I moved over from Deluge after many years and it's amazing this is actively maintained even after so long

### CODE REVIEW

**Comment by leewc** [comment]
Thanks, my miss on the typo :(

**Comment by pkishino** [comment]
my bad..clicked the wrong button..
I"ll recreate this

**Comment by pkishino** [comment]
fixed in 445261aa4cfa81bc3c71e4f4d8607ba048d9c4bf

**Comment by leewc** [comment]
Cool, thanks. I originally had the change on `master` but the template on PR said to use `dev`...

**Pull request closed without merging**
