### PR TITLE
WIP at adding iptest and ip route harding

### PR DESCRIPTION
**Pull request by pkishino**
Hey,
I started this today with some input from #1134 and #1166 but got stuck with getting transmission port check to work.. would be great if someone could take a look and improve this, mostly just hacked together, not too familiar with the ip routing stuff
also could include ideas from #1127

### CODE REVIEW

**Comment by martinruenz** [comment]
You might find the 'kill switch' implementation of protonvpn interesting, which is based on iptables: https://github.com/ProtonVPN/linux-cli/blob/1190545a4293332824b28fe442f95f7be44b65d5/protonvpn_cli/connection.py#L764

**Comment by sylphaenos** [comment]
Hey there, this PR was originally supposed to close several other **very** important security-related issues (#1134, #1127). Is this still planned?

**Comment by pkishino** [comment]
@haugene  some of this stuff might no longer be needed based on latest but there are still Harding things that are needed

**Comment by haugene** [comment]
Ok. We should have a sync then. Try to sum up the issues on potential DNS leak and route hardening and find a good way to introduce it where we try not to break things. I think most of the hardening should be a well documented opt-in feature to begin with. Try it out on those who are most interested in it and then change the defaults gradually.

**Comment by sylphaenos** [comment]
Sorry to be a bother, but could we get this PR excluded from stale bot (or should I open another issue for security hardening?)

**Comment by pkishino** [comment]
I think a new PR with updates following latest improvements would be best, haven’t had much time recently to dev..

**Pull request closed without merging**
