### PR TITLE
Add LOG_TO_STDOUT environment variable + documentation

### PR DESCRIPTION
**Pull request by kushagharahi**
The environment variable `DOCKER_LOG`, when set to `true` already logs Transmission logs to stdout. In my opinion this is a poor name, so I added a new variable `LOG_TO_STDOUT` and added documentation for it. I've left `DOCKER_LOG` in to ensure backwards compatibility. 

Regarding 3.x: I can open a second PR once this gets merged to remove `DOCKER_LOG` in the 3.x branch.

If the reviewers do not like the depreciation of `DOCKER_LOG` and introduction of `LOG_TO_STDOUT` then I can update this PR to just be documentation of the environment variable `DOCKER_LOG`.

### CODE REVIEW

**Comment by pkishino** [comment]
I think you mean DOCKER_LOG, right?

**Comment by kushagharahi** [comment]
@pkishino yes, super awkward. my mistake!

**Comment by pkishino** [comment]
Sure, I’m fine with this if you could just squash all the commits into one please, then I can merge it cleanly.  And for 3.x is fine to drop the old

**Comment by kushagharahi** [comment]
@pkishino Done, squashed all the commits into one. I'll put out a 3.x PR when this is merged.

**Pull request merged**
