### PR TITLE
Display WAN IP

### PR DESCRIPTION
**Pull request by AustinSaintAubin**
Display WAN IP in Console

### CODE REVIEW

**Comment by AustinSaintAubin** [comment]
This addition might be best to do to ( /etc/transmission/updatePort.sh )

**Comment by haugene** [comment]
Hi, and thanks for contributing to the container!

Just so I understand the reason for this change. You want to know the IP you're on before connecting to VPN? OpenVPN starts on the next line, so you won't see that if this is executed before.

**Comment by AustinSaintAubin** [comment]
I want to know my WAN ip before and after VPN connection is established. In a newer commit on my container I put the display wan ip command in one of the transmission shell scripts so it's the last to run.

**Comment by haugene** [comment]
Wanna update this PR with that? So we get both IP's posted in the logs?

**Comment by himred** [comment]
This can be done with the new "Custom pre/post scripts" feature.

- Mount /scripts
- Create a file named /scripts/transmission-post-start.sh
- Make the script executable using : `chmod a+x /scripts/transmission-post-start.sh`
- Edit the script and put this code inside:

```
#!/bin/bash
ip=$(curl -s 'https://api.ipify.org?format=json' | cut -f4 -d'"')
echo "Current WAN IP is : $ip"
```

You can read the documentation about Custom pre/post scripts for details.

**Comment by AustinSaintAubin** [comment]
Awesome, finally tested at that works!

**Pull request closed without merging**
