### PR TITLE
Adding files for Privado VPN (Newshosting replacement)

### PR DESCRIPTION
**Pull request by Sean89us**
On Feb 19, the Newshosting VPN will be discontinued in favor of the new replacement, [Privado](https://privado.io/). Existing Newshosting VPN subscribers will have gotten an email about the change with a link to sign up for Privado VPN at no cost.

These ovpn files came straight from privado and were lightly modified to support docker-transmission-openvpn
```auth-user-pass /config/openvpn-credentials.txt```
[Link here](https://privado.io/apps/ovpn_configs.zip)

### CODE REVIEW

**Comment by Sean89us** [comment]
@haugene Please review, this is time sensitive as Newshosting will be discontinuing their VPN service on Feb 19

**Comment by haugene** [comment]
Hey @Sean89us. This looks good to me. Thanks for contributing 😄
Should we also just remove Newshosting? Or wait until 19th? Either way, the "supported providers" doc should be updated.

**Comment by Sean89us** [comment]
@haugene  I updated the documentation. After the 19th I will create another PR to remove newshosting

**Comment by haugene** [comment]
I'm merging to master now so it will be available on the latest tag. Then you can verify that it works etc. After the 19th when we remove Newshosting I'll tag a new release.

Thanks again for helping to keep the image up to date.

**Pull request merged**
