### PR TITLE
Add support for ElasticTunnel VPN provider

### PR DESCRIPTION
**Pull request by ishatravka**
This PR adds support for [ElasticTunnel VPN Provider](https://elastictunnel.com/).

Supported regions:
- Canada, Toronto. OPENVPN_CONFIG value - `canada_toronto`
- Germany, Frankfurt. OPENVPN_CONFIG value - `germany_frankfurt`
- Netherlands. OPENVPN_CONFIG value - `netherlands`
- UK, London. OPENVPN_CONFIG value - `uk_london`
- Ukraine. OPENVPN_CONFIG value - `ukraine`
- USA, NY. OPENVPN_CONFIG value - `usa_ny`
- USA, SF. OPENVPN_CONFIG value - `usa_sf`

docker run argument values example:
```
docker run --cap-add=NET_ADMIN -d \
...
              -e OPENVPN_PROVIDER=ELASTICTUNNEL \
              -e OPENVPN_CONFIG=canada_toronto \
...
```

### CODE REVIEW

**Comment by haugene** [comment]
LGTM 👍 Thanks for contributing!
Should also add it as a new provider in the documentation, but I'll do that and merge this now.

**Comment by ishatravka** [comment]
Thank you so much @haugene. 
When should I expect these changes to go to master to be present on a latest docker image? I am not sure what is the release process that you have there.

**Comment by haugene** [comment]
Hey again @ishatravka. My release process has been very ad hoc. The thought was to do a new release for each merge to master, but I've diverged from that. Using the Docker Hub for builds I had to configure builds for each tag and with 4 distros supported (ubuntu, alpine, arm64, armhf) there was more work. It doesn't take much time of course, but over time anything gets tedious.

Anyways. Made my life simpler now with CircleCI. So I'll tag a release at the current master version. Then merge from dev and tag again. Going forward I'll do more frequent releases. It also helps me in the end because it will be easier for everyone to debug errors and tell me which version is breaking.

**Comment by ishatravka** [comment]
Hey @haugene, thank you! Just switched to latest tag, works perfect.

**Pull request merged**
