### PR TITLE
Feature: Move documentation to GitHub pages

### PR DESCRIPTION
**Pull request by zoispag**
Feature: Move documentation to GitHub pages. Documentation build with mkdocs.

#362

image

Need to configure the build step (CircleCI or TravisCI) to build in a **gh-pages** branch.

Example can be found [here](https://zoispag.github.io/docker-transmission-openvpn/)

### CODE REVIEW

**Comment by haugene** [comment]
Sweet! Thanks a lot @zoispag, this looks really good! 👍 
I'll have a look at setting up the CircleCI build and merge it soon.

**Comment by zoispag** [comment]
Can help with that as well. Let me know if you need my help! ✌🏼

**Comment by zoispag** [comment]
@haugene to manually push the docs, pull and run `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material`.
This will create a `gh-pages` which will publish the documentation.

**Comment by haugene** [comment]
Thanks again, works like a charm! Had to run it with "gh-pages" command but figured it out 👍
I'll have another look at CircleCI later. Should be automated.

**Pull request merged**
