### PR TITLE
Update configure-openvpn.sh

### PR DESCRIPTION
**Pull request by Dupontem**
https://www.ipvanish.com/software/configs/configs.zip  redirects to a html page
https://configs.ipvanish.com/configs/configs.zip  is the right URL 

## Breaking change

```txt
<placeholder>
```

## Proposed change

```txt
<placeholder>
```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to a this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by kukkamario** [comment]
I just got hit by this same issue and reached same conclusions.

Hopefully this can soon be merged :+1:

**Comment by Areustle** [comment]
PR addresses Issue 123 in https://github.com/haugene/vpn-configs-contrib/issues/123. 

I have built and tested this PR locally and can confirm it resolves the IPVanish config resolution issue.

**Comment by resuarez** [comment]
As workaround until the solution is published.  I've mapped  /etc/openvpn/ipvanish/ to external folder and I've placed the updated version of configure-openvpn.sh.  The file needs to be owned by nobody:users and maked as executable.

I can confirm too that new URL works

**Comment by Stormer99** [comment]
> As workaround until the solution is published. I've mapped /etc/openvpn/ipvanish/ to external folder and I've placed the updated version of configure-openvpn.sh. The file needs to be owned by nobody:users and maked as executable.
> 
> I can confirm too that new URL works

Sorry to bother, but do you think you can expand of this work around. I've mapped the volume for /etc/openvpn/ipvanish/ and placed the updated version of configure-openvpn.sh (I just changed the URL)  and changed the ownership to nobody:users.  It still doesn't work but the log shows a different problem.

Starting container with revision: 44c82aa1297b0f4473ad141f2cea326b407d9c22
Creating TUN device /dev/net/tun
Using OpenVPN provider: IPVANISH
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for IPVANISH. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.VCwYStb3VH
Extracting configs to /tmp/tmp.rpz3ZZRCfL
Found configs for IPVANISH in /tmp/tmp.rpz3ZZRCfL/vpn-configs-contrib-main/openvpn/ipvanish, will replace current content in /etc/openvpn/ipvanish
rm: cannot remove '/etc/openvpn/ipvanish': Device or resource busy
Cleanup: deleting /tmp/tmp.VCwYStb3VH and /tmp/tmp.rpz3ZZRCfL
3 servers found in OPENVPN_CONFIG, ipvanish-ES-Madrid-mad-a10 chosen randomly
Supplied config ipvanish-ES-Madrid-mad-a10.ovpn could not be found.
Your options for this provider are:
NB: Remember to not specify .ovpn as part of the config name.

Thanks

**Comment by snoopyh42** [comment]
One more confirming.  Made this change locally and built the docker image.  Now having no problems launching and connecting to IPVanish VPN using this container.

**Comment by Stormer99** [comment]
> As workaround until the solution is published. I've mapped /etc/openvpn/ipvanish/ to external folder and I've placed the updated version of configure-openvpn.sh. The file needs to be owned by nobody:users and maked as executable.
> 
> I can confirm too that new URL works

Can you please post the changes you made to the configure-openvpn.sh file?   thanks

**Comment by ilike2burnthing** [comment]
@pkishino

**Pull request merged**
