### PR TITLE
Added configs for NordVPN

### PR DESCRIPTION
**Pull request by reavessm**

### CODE REVIEW

**Comment by haugene** [comment]
Hi. First of all - thanks for wanting to contribute to this project!

You don't have a description of your changes or why you think they should be added. The feature proposed in #655 and implemented in #728 was much anticipated and also removed the need for having NordVPN configs in the repo at all.

Are you aware of this feature, and do you still mean that some configs should be checked in?
Please describe your reason and I'll consider the addition.

**Comment by reavessm** [comment]
I was not aware of that feature.  The documentation makes it seem like there has to be a file in the repo to select from.

> "The `OPENVPN_CONFIG` is an optional variable. If no config is given, a default config will be selected for the provider you have chosen. Find available OpenVPN configurations by looking in the openvpn folder of the GitHub repository. The value that you should use here is the filename of your chosen openvpn configuration without the .ovpn file extension"

Unless this means that I _have_ to use the default nordvpn config?  Am I unable to select different countries with nordvpn?

**Comment by haugene** [comment]
You're right. The documentation is not detailing the NordVPN integration at all and that is unfortunate.
This is the first integration of that kind and for all other providers it's file based.

See if you can find some answers reading issue #758 and related issues/PRs. You can also have a look at the script: https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/nordvpn/updateConfigs.sh

There are also default set up here when it comes to category and protocol: https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L32

But yes, you should be able to define a country to get server for.
If you figure it all out I'd gladly merge an update to the README 😄

**Comment by edgd1er** [comment]
Here some information
Available ENV variables in the container to define via the NORDNVPN API the file to use are:
NORDVPN_COUNTRY: (values: https://api.nordvpn.com/v1/servers/countries)
NORDVPN_CATEGORY: (values: https://api.nordvpn.com/v1/servers/groups)
NORDVPN_PROTOCOL: tcp or udp ( more available at https://api.nordvpn.com/v1/technologies, ut need script adaptation)

the file is then download using the API to find the best server according to the variables, here an albanian, using tcp:
https://api.nordvpn.com/v1/servers/recommendations?filters[country_id]=2&filters[servers_technologies][identifier]=openvpn_tcp&filters[servers_groups][identifier]=&limit=1

**Comment by haugene** [comment]
Closing this now as there are several PRs coming to fix #832 and #842 is updating the README.
New docs are published. Feel free to submit a new PR with updates or enhancements to that one instead.

See: https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/

**Pull request closed without merging**
