### PR TITLE
updated all mullvad profiles

### PR DESCRIPTION
**Pull request by XenGi**
This superseeds #1433

### CODE REVIEW

**Comment by XenGi** [comment]
Script that created this:
```sh
#!/bin/sh

repo=~/docker-transmission-openvpn
mullvad_config=~/mullvad_config_linux

#rm $mullvad_config/mullvad_userpass.txt
cd $mullvad_config
for d in $(ls *.conf); do
    sed -i 's/mullvad_ca.crt/\/etc\/openvpn\/mullvad\/ca.crt/' $d
    sed -i 's/mullvad_userpass.txt/\/config\/openvpn-credentials.txt/' $d
    sed -i 's/up /#up /' $d
    sed -i 's/down /#down /' $d
    mv $d ${d/mullvad_/}
    mv $d ${d/.conf/.ovpn}
done
cp $mullvad_config/mullvad_ca.crt $repo/openvpn/mullvad/ca.crt
cp $mullvad_config/update-resolv-conf $repo/openvpn/mullvad/update-resolv-conf
cp $mullvad_config/*.ovpn $repo/openvpn/mullvad/
```

**Comment by haugene** [comment]
Looks good :+1:
Thank you for going another round here and helping out :clap:

**Comment by garret** [comment]
Sorry, I will say it for the 10th time but the servers do not work as I always get the `[..] dev tun0 RTNETLINK answers: Permission denied [..]` error :/

**Comment by XenGi** [comment]
Hi @garret, I guess this is another issue as this seems to be only a problem with your setup. Maybe open another ticket for that issue.

**Comment by haugene** [comment]
I saw you commented in another issue @garret. This is solved on your end? Or is it still something to look into?

**Comment by garret** [comment]
@haugene yes, I tried again even with the new v3.2 and still get the same error with the container not working. Honestly, I am surprised it is only me. Thus, to make it working I am using a modified version of the .ovpn file. I will open an issue to see if it is only me.

**Comment by Flight777** [comment]
Can confirm I also still have this issue and specifically need to disable IPv6

**Comment by AKDub** [comment]
Is there any way to add the temporary fix to a docker-compose file?

**Pull request merged**
