### PR TITLE
Automate PrivateVPN configs

### PR DESCRIPTION
**Pull request by arpaulnet**
The existing PrivateVPN configuration files do not span all of the PrivateVPN servers or options.  This update contains an `updateConfigs.sh` script along with new and updated `*.ovpn` files for PrivateVPN.

The script does the following:
1. Downloads/unpacks a zip file from PrivateVPN's support
2. Modifies the config files to match the previous OpenVPN options
3. Generates additional optional config files:
   - `tcp` = use `tcp` port `443`
   - `strong` = use `AES-256-CBC` cipher
   - `dedicated` = uses PrivateVPN's "dedicated ip" option (note: all ports are open, beware `WEBPROXY_ENABLED`)
4. Organizes the config file names to be relatively human-friendly
5. Creates links to maintain backward-compatibility with existing references to configuration files

### CODE REVIEW

**Comment by haugene** [comment]
Great stuff, thanks for contributing 👍 
Always great to get update scripts for the providers and it's a good fit with #1110 initiative going on.

Merging now to dev, but will do a new release right away so it will be on :latest and release tag very soon. I guess you've already tested this locally, but if you could also verify it in the final image that would be great.

**Comment by arpaulnet** [comment]
Thanks 😄. I spot-checked a handful of the connections in the final image, and they were working as expected.

**Comment by doctorjei** [comment]
This commit seemed to have removed the port-forwarding update/fix from issue #1061. I think we need an addition to automatically generate the port-forward versions.

**Comment by doctorjei** [comment]
I fixed the port-forwarding issue and added it to the PrivateVPN automation script: https://github.com/haugene/docker-transmission-openvpn/pull/1587

**Pull request merged**
