### PR TITLE
Added fallback and more explicit warning message

### PR DESCRIPTION
**Pull request by pkishino**
## Proposed change

```txt
This will use /data/transmission-home (previous default) as fallback if the folder exists.

```

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to a this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated

### CODE REVIEW

**Comment by pkishino** [comment]
Yeah, I understand. I’ll remove the migrate and just add a message instead

**Comment by pkishino** [comment]
Wording might need to be changed..
You shouldn’t set TRANSMISSION_HOME to /config but to a subdirectory.. like
/config/transmission-home ../config is the mount point

**Comment by pkishino** [comment]
thanks for the details..
when you wrote:

   - changed the TRANSMISSION_HOME variable

what did you change it too?

**Comment by ilike2burnthing** [comment]
From /config/transmission-home to /config

**Pull request merged**
