### PR TITLE
Added trust.zone provider

### PR DESCRIPTION
**Pull request by Maximillion195**

### CODE REVIEW

**Comment by haugene** [comment]
Hey. Please also add TrustZone in the list of providers in the README.

**Comment by haugene** [comment]
Hello again. Sorry I'm doing this a bit scattered. Looking through it again I see a couple of more things.
This config has ping and ping-restart defined. We're recommending to use ping and ping-exit (documented [here](https://github.com/haugene/docker-transmission-openvpn#restart-container-if-connection-is-lost)).

The reason for ping-exit is that the openvpn restart has not been working well in the container and it just freezes. If we do ping-exit, openvpn should exit and the --restart=unless-stopped flag to Docker will make it restart the whole container instead of just openvpn.

Could you also remove those config lines, and I'll merge :)

**Comment by Maximillion195** [comment]
Hey, not a problem mate. Makes sense :) I have removed those lines.

**Comment by haugene** [comment]
Allright, merging. Thanks for contributing and let me know how testing it from the dev tag goes. Will do a merge to master and a new release - probably today :)

**Comment by mrjackyliang** [comment]
Looks like this has been added, marking into #554!

**Pull request merged**
