### PR TITLE
Update windscribe configs

### PR DESCRIPTION
**Pull request by trananhtuan**
## Breaking change

```txt
<placeholder>
```

## Proposed change

```txt
Windscribe has rolled out a new OpenVPN certificate authority and phased out OpenVPN compression recently. The old CA no longer works. 

Source: https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222?gi=81f3486419a7
```

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to a this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [ x] The code change is tested and works locally.
- [ x] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by ConnorH1** [comment]
Looking forward to this update so my container can run again.

**Comment by pkishino** [comment]
please check the devbranch and the new vpn config repo...they are already merged in there.
We are not going to merge in any new or updated configs to this repo any more

**Comment by trananhtuan** [comment]
OK no problem

**Comment by pkishino** [comment]
please redirect all config updates to https://github.com/haugene/vpn-configs-contrib/pulls

**Pull request closed without merging**
