### PR TITLE
VPN Unlimited  

### LINKED ISSUE #766: VPN Unlimited provider
Hey guys!
I recreate an issue to handle VPN Unlimited provider. The old global issue is here: https://github.com/haugene/docker-transmission-openvpn/issues/554

**Which provider?**
VPN Unlimited - https://www.vpnunlimitedapp.com

**Where are the configs?**
Here is the latest openvpn config:
[634437CA6F37ACCCA2DA8769F673F554_default_openvpn.zip](https://github.com/haugene/docker-transmission-openvpn/files/3026520/634437CA6F37ACCCA2DA8769F673F554_default_openvpn.zip)

Let me know if you need more info ;) 

I can try to make a PR if it's simple to implement =)

Cheers!

### PR DESCRIPTION
**Pull request by Nightbr**
Hey,

here is a PR to support Unlimited VPN, I put this in Draft, feel free to make comments and ask me any change it requires!

close #766

### CODE REVIEW

**Comment by Nightbr** [comment]
Hi @haugene, let me know if the config is ok. 
The ca and cert is embedded in all ovpn files (like vyprvpn and other I have seen). But there is also a private, I don't know if I have to remove it or not. If you have an idea.

Thanks for your help ;)

**Comment by emirdora** [comment]
> Seems to be an issue with "NO PORT UPDATER FOR THIS PROVIDER" I don't know, here is the container logs

https://github.com/haugene/docker-transmission-openvpn/blob/f4c9cf50f795425208e8e159207acdcea830810e/transmission/start.sh#L66-L76

@Nightbr, this looks normal to me. Anyway, you can test the config as mentioned here: https://github.com/haugene/docker-transmission-openvpn#using-a-custom-provider

:)

**Comment by haugene** [comment]
Hello Titouan, and sorry for the late response on this. It's too easy to postpone these types of things when work and personal life gets hectic.

Your changes looks good! 👍 You're probably running your own build so you know it works well?
I'm going to merge it now. Let me know when/if you get to verify it using the official build.

And thanks again for contributing!

**Comment by Nightbr** [comment]
Seems to work correctly since the "NO PORT UPDATER FOR THIS PROVIDER" is not an issue. I will try with the official Build when I have some spare time ;) 
Thanks for the help & review!

**Comment by haugene** [comment]
Sweet. No, that's not an issue. The "caps lock" printing might be a bit over the top. It's really old code from the time where PIA was close to the only provider and I thought that most providers would hava a port updating script. Turns out that most providers don't support it - so it's more of the exception than the rule.

**Pull request merged**
