### PR TITLE
New API for open port lookup

### PR DESCRIPTION
**Pull request by Zeelia**
The PrivateVPN API for looking up the opened forwarded port has changed.
I tried forking the dev branch, but this file didn't exist there. It's my first fork, sorry if I made it the wrong way...

## Proposed change

```txt
Changing the URL to the PrivateVPN open port lookup API.
At the moment the script is unable to lookup the opened port. 
This change was necessary to fix the access to the new API URL.
```

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to a this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- There doesn't seem to be any opened issues claiming problems with the current script, but it is easy to miss that the script is failing if you don't check the logs. The docker container works without a problem even if this script fails, as it is not critical. Additionally, the old API was working until recently, so users might not have noticed the change yet. 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Review by pkishino — APPROVED** [review]
great to see the update :)

**Comment by HendrikRoth** [comment]
Unfortunality, i have still the same issue here.

**Comment by Zeelia** [comment]
> Unfortunality, i have still the same issue here.

I double checked if my setup was still working, but it is indeed not working. The script itself seems to be fine as I have tested it on another machine. However, when I open bash inside of my docker container, I'm not able to run curl to PrivateVPNs API. I suspect it has something to do with their Cloudflare protection, as curl is currently throwing HTTP 403 Forbidden.
This doesn't happen on my other machine which is running without VPN.

I'm not sure how to authenticate the server to Cloudflare though, if this is in fact the issue.

Here is the verbose log of curl:
```
bash# /etc/openvpn/privatevpn/update-port.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.26.2.3:443...
* Connected to connect.pvdatanet.com (104.26.2.3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2221 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [79 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jul 18 00:00:00 2020 GMT
*  expire date: Jul 18 12:00:00 2021 GMT
*  subjectAltName: host "connect.pvdatanet.com" matched cert's "*.pvdatanet.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f95defa90)
} [5 bytes data]
> GET /v3/Api/port?ip[]=xx.xx.xx.xx HTTP/2
> Host: connect.pvdatanet.com
> user-agent: curl/7.77.0
> accept: */*
>
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
} [5 bytes data]
< HTTP/2 403
< date: Mon, 07 Jun 2021 18:16:51 GMT
< content-type: text/plain; charset=UTF-8
< content-length: 16
< x-frame-options: SAMEORIGIN
< cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< expires: Thu, 01 Jan 1970 00:00:01 GMT
< cf-request-id: 0a894a299a00001699448cb000000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=u41sblaxNaFNjC0KfDZ9w6jsoXUB9SKYItFHGuD5ZPL%2BAIpUAJF83uU2xaXMlr0SmTPTRyIXKKbTeZhJrZKvw6c%2FsFaeDuFB8Z2vWoIdZp7w2eOVIqGZ6BB%2BgRUiahjVM0Y%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 65bbdfbc2a131699-ARN
<
{ [16 bytes data]
100    16  100    16    0     0     55      0 --:--:-- --:--:-- --:--:--    55
* Connection #0 to host connect.pvdatanet.com left intact
```

**Comment by Zeelia** [comment]
I just tested it right now, and it's working again, without any changes from my side. I don't know why. The only thing I can imagine is that too many people connect to the same VPN server, and the requests congest Cloudflare protecting PrivateVPNs API, thinking that we are robots or something...

**Pull request merged**
