### PR TITLE
OVPN script added - rebased to dev

### PR DESCRIPTION
**Pull request by derekcentrico**
Continuation of https://github.com/haugene/docker-transmission-openvpn/pull/2283, rebasing to dev.

### CODE REVIEW

**Comment by derekcentrico** [comment]
> Continuation of #2283, rebasing to dev.

Please remember that the contrib needs to have my PR added alongside this otherwise it will break for users.  It relies upon those added VPN configurations for the new internal script.

**Comment by pkishino** [comment]
please edit the commit, it should ONLY contain YOUR commit, no others.

**Comment by derekcentrico** [comment]
> 

@pkishino apologies, is this directed to me?  I only pushed the ovpn per my commit unless I'm missing something.

Happy to fix whatever if I erred.

**Comment by pkishino** [comment]
please check above, it also includes a number of other commits, please edit and rebase and make sure it only includes your commit and none of the others.

**Comment by derekcentrico** [comment]
Could not edit this one (probably just dumb and couldn't figure it out on the UI).  #2317 replaces and has just my file added.

**Pull request closed without merging**
