### PR TITLE
Tranmission 4.0.4 and added an echo to OVPN script 

### PR DESCRIPTION
**Pull request by derekcentrico**
The change edits the Dockerfile to upgrade to Transmission 4.0.4.  

A very minor echo added for logging steps of the OVPN provider script.

### CODE REVIEW

**Comment by pkishino** [comment]
Already bumped dev branch to 4.0.4 ;) let’s see if I can get around to updating master and making a new release this week

**Comment by derekcentrico** [comment]
@pkishino can you go ahead and partial approve the other part?

**Comment by pkishino** [comment]
I’ll add in that print statement separately

**Comment by derekcentrico** [comment]
Perfect!

**Pull request closed without merging**
