### PR TITLE
Fetch PIA configs on startup - change to nextgen servers

### LINKED ISSUE #1334: Update PIA configs to next gen servers
**Which provider?**
PIA

**Where are the configs?**
Should probably update to the next gen servers.

https://www.privateinternetaccess.com/helpdesk/news/posts/august-19th-2020-important-updated-server-changes-and-related-issues

### PR DESCRIPTION
**Pull request by haugene**
Resolves #1334 

Deleted all configs that are built into the image and created a script that downloads configs on startup.

### CODE REVIEW

**Comment by haugene** [comment]
No objections, let's merge it and see how it works 😊

**Comment by cpaucar3** [comment]
I just pull and redeploy right? No compose changes needed? I'll be happy to test after the merge.

**Comment by haugene** [comment]
Great :+1: Yes, that should do the trick. As long as you are using the dev tag of the image already? If not you need to add :dev to the image. There are some changes on dev but most of it is backwards compatible.

New image is built so it's ready to be pulled.

**Comment by cpaucar3** [comment]
I'm not using :dev but when I add it I get an error:
`ERROR: The Compose file is invalid because:
Service transmission-openvpn has neither an image nor a build context specified. At least one must be provided.`

Here is the snippet from my file. The only thing I added was :dev like you said.
```
   transmission-openvpn:
     cap_add:
     - NET_ADMIN
     container_name: transmission-openvpn
     environment:
       CREATE_TUN_DEVICE: "true"
       OPENVPN_CONFIG: Spain
       OPENVPN_PASSWORD: ${PASS}
       OPENVPN_PROVIDER: PIA
       OPENVPN_USERNAME: ${NAME}
       PGID: 113
       PUID: 107
       TRANSMISSION_DOWNLOAD_QUEUE_ENABLED: "false"
       TRANSMISSION_MAX_PEERS_GLOBAL: 9999
       TRANSMISSION_PEER_LIMIT_GLOBAL: 9999
       TRANSMISSION_PEER_LIMIT_PER_TORRENT: 9999
       TRANSMISSION_PORT_FORWARDING_ENABLED: "true"
       TRANSMISSION_RATIO_LIMIT: 0
       TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
       TRANSMISSION_UMASK: 0
       TZ: ${TZ}
       WEBPROXY_ENABLED: "false"
       image: haugene/transmission-openvpn:dev
     logging:
       driver: json-file
       options:
         max-size: 10m
     networks:
       smarthome:
         ipv4_address: ${IP}
     ports:
     - published: 9091
       target: 9091
     restart: always
     volumes:
     - ${PATH}:/data
     - /etc/localtime:/etc/localtime:ro
 version: '3.8'
```
I also pulled the dev image already
```
$ docker pull haugene/transmission-openvpn:dev
dev: Pulling from haugene/transmission-openvpn
df20fa9351a1: Already exists
94e1ba03f4d6: Pull complete
4f405c732565: Pull complete
b4aff87d54d7: Pull complete
b520c96547fc: Pull complete
e3496ab45dd8: Pull complete
Digest: sha256:27a1d5c84fa805be749eeca22b38e8a1b0a1483de3a78bfe81460a7ea3ebd5d4
Status: Downloaded newer image for haugene/transmission-openvpn:dev
docker.io/haugene/transmission-openvpn:dev
```

**Comment by haugene** [comment]
It looks like your `image` key has been indented and is now under environment variables?

**Comment by cpaucar3** [comment]
Well that's embarrassing... well here is the end of the logs if you're curious.
```
Overriding umask because TRANSMISSION_UMASK is set to 0
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 107:113
BusyBox v1.31.1 () multi-call binary.

Usage: chown [-RhLHPcvf]... USER[:[GRP]] FILE...

Change the owner and/or group of each FILE to USER and/or GRP

        -R      Recurse
        -h      Affect symlinks instead of symlink targets
        -L      Traverse all symlinks to directories
        -H      Traverse symlinks on command line only
        -P      Don't traverse symlinks (default)
        -c      List changed files
        -v      List all files
        -f      Hide errors
Setting permission for files (644) and directories (755)
BusyBox v1.31.1 () multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

Each MODE is one or more of the letters ugoa, one of the
symbols +-= and one or more of the letters rwxst

        -R      Recurse
        -c      List changed files
        -v      List all files
        -f      Hide errors
Setting permission for watch directory (775) and its files (664)
BusyBox v1.31.1 () multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

Each MODE is one or more of the letters ugoa, one of the
symbols +-= and one or more of the letters rwxst

        -R      Recurse
        -c      List changed files
        -v      List all files
        -f      Hide errors

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    107
User gid:    113
-------------------------------------

STARTING TRANSMISSION
Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=yes
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Wed Oct 14 19:48:05 2020 Initialization Sequence Completed
Generating new client id for PIA
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 7
```

**Comment by Anon0ne** [comment]
@haugene I also downloaded dev image just a moment ago, and port forward script isn't working for me either. Not for DE Frankfurt or Israel.

I opened the container and ran the port forward script manually, and got this error:

```
awk: bad regex '{|:|}': Repetition not preceded by valid expression
./portforward.sh: line 35: [: : integer expression expected
```

**Comment by cpaucar3** [comment]
@Anon0ne the web UI on port 9091 also no longer loads for me.

**Comment by Anon0ne** [comment]
> @Anon0ne the web UI on port 9091 also no longer loads for me.

@cpaucar3 I went back to :latest build and started right up... oddly enough the port forward worked also?!

**Comment by cpaucar3** [comment]
I gave it one more shot and nothing changed. Might try it later this weekend.

**Comment by haugene** [comment]
Thanks for posting your logs @cpaucar3. Seems there is a syntax error in the chown scripts after the switch to alpine maybe?

Anyways. The port forward script will not work on dev yet. We've now changed the configs and the script needs to be updated.
And @Anon0ne. It seems the port forwarding on the old servers will work once in a while. But as they're migrating servers it will get less and less likely that you'll hit a server that supports it. If I understand it correctly. And they do not try to fix any bugs on this in the last weeks on operations. So we need to get the new script into the container.

**Comment by markchaik** [comment]
@haugene will this make its way into :latest, or do I need to switch to :dev?  Several PIA servers not working as of today.  Thx.

**Comment by haugene** [comment]
For future reference. It is now on master 👍😁

**Pull request merged**
