### PR TITLE
Correct the github hyperlink for Flood Web UI

### PR DESCRIPTION
**Pull request by gigawatts**
Per https://github.com/haugene/docker-transmission-openvpn/issues/1734

### CODE REVIEW

**Review by haugene — APPROVED** [review]
Thanks :+1:

**Comment by haugene** [comment]
Closes #1734

**Comment by ilike2burnthing** [comment]
Was this supposed to be merged?

**Comment by haugene** [comment]
Hah! 😅 I just approved it and closed 🤦‍♂️

**Pull request merged**
