### PR TITLE
Added BasicAuth to tinyproxy, updated docs and dockerfiles

### LINKED ISSUE #1203: Support basic authentication for TinyProxy
**Is your feature request related to a problem? Please describe.**

Currently, this docker image doesn't support setting authentication for TinyProxy, so if a user deploys it on a seedbox, the web proxy can be accessed by anyone on the web, which can be easily abused and is very dangerous.

**Describe the solution you'd like**

Allow the user to set `WEBPROXY_USERNAME` and `WEBPROXY_PASSWORD` environment variables.

Documentation about the basic authentication of TinyProxy is [here](https://github.com/tinyproxy/tinyproxy/wiki/user-&-password).

**Describe alternatives you've considered**

Nothing

**Additional context**

Nothing

### PR DESCRIPTION
**Pull request by pkishino**
fix #1203 
This commit also added some small items to dockerfile, upgraded ubuntu one to 19.10 (had to to support tinyproxy basicauth etc)

### CODE REVIEW

**Comment by haugene** [comment]
Awesome! Looks good, and it's a wanted feature for sure.
Thanks a lot for carrying the project forwards 👍 

There's a couple of apt-get install lines that don't end with a space before the \ sign, but that's just codestyle and I don't have any comments on the code itself.

Btw. I have kind of decided that we should drop support for both ubuntu and alpine image and just do alpine by default. Haven't done it yet and wanted to get some feedback. What do you think?

**Comment by pkishino** [comment]
> Awesome! Looks good, and it's a wanted feature for sure.
> Thanks a lot for carrying the project forwards 👍
> 
> There's a couple of apt-get install lines that don't end with a space before the \ sign, but that's just codestyle and I don't have any comments on the code itself.
> 
> Btw. I have kind of decided that we should drop support for both ubuntu and alpine image and just do alpine by default. Haven't done it yet and wanted to get some feedback. What do you think?

I'll fix the line ends and I gully agree with the alpine image !

**Comment by haugene** [comment]
> I'll fix the line ends and I gully agree with the alpine image. I don't see any advantage with keeping three different platform support

Then let's do it 😄 The weather forecast is just too good in Oslo to stay inside these days, but hoping to get some coding time soon. Seems there are clouds in the horizon, or in the forecast at least ;)

**Comment by pkishino** [comment]
haha, yeah, when oslo has nice weather its awesome :)

**Pull request merged**
