### PR TITLE
Update healthcheck script

### PR DESCRIPTION
**Pull request by RickyXwang**
See #1306 
Update
1. Change ping -c 1 to -c 5, should avoid the issue with unstable network or light packet loss.
2. Move interface check to the front
3. Added date-time output to better log
4. If SIGUSR1 did not work use HUP
5. Added logic to check if the ping used tun dev

### CODE REVIEW

**Comment by RickyXwang** [comment]
We can hold on to this for now. Making an update to address issues with multiple tun dev fond and DNS return ipv6 address instead of ipv4.

**Comment by haugene** [comment]
Hey @RickyXwang. Thanks for addressing this issue, and for all your help on answering issues. Greatly appreciated!

As for this change. It looks good and is probably more stable than today's script so I'm tempted to just merge it. I'm then assuming that ping will give a 0 exit code as long as at least one response is given?

Another thing though. I was actually quite surprised to see that the health check script was killing openvpn. I must have forgotten that was there. I think it feels a bit wrong. A health check script should check the health and not do this kind of intrusive action, what do you think?

**Comment by haugene** [comment]
Regarding my last comment about health check script being non-intrusive. Have a look at the last comments about using autoheal companion container in #454. What do you think about introducing this as the "official" solution to the problem for now?

**Comment by RickyXwang** [comment]
I do agree that healthcheck should be just a health check, will move the restart out somewhere. For the autoheal container, it sounds like a good solution be seems like to me it hasn't been updated for a while (the latest version from 2 years ago). It also has some issues working with docker-compose as the label doesn't work in compose (I think quite a lot of folks do use compose here). I will keep looking and see if we got any other options or a more maintained project for this.

**Comment by haugene** [comment]
Great! :+1: I added the label to the project so they should be there by default. It was also reported in the other issue that adding them locally was a struggle. If we end up proposing another companion-service here then we can adapt to it instead.

**Comment by haugene** [comment]
Hey again. I just reverted the last change to the healthcheck script. I've been seeing the log message `event_wait : Interrupted system call (code=4)` in multiple issues and I'm suspecting that it's the health check script that is interrupting openvpn.
The container might not function anyways, as the health check reports it as being broken - but wanted to try and see if it resolved anything. So you'll have to rebase against that as well. But I'm all for a better health check script, so ping me when you feel this is ready to be merged.

**Comment by RickyXwang** [comment]
I think, for now, I can make this new version of `healthcheck` to a recovery script and have it run separately, set a flag to enable it from the start script. 
We are facing lots of people having issues because
1. They are new and start to set things up
2. They changed some config that is not supposed to be changed or using the old configuration in the new image.
3. Some updates (We made or the VPN server-side change) broke the previous working configure and now require some change.

And If the script is trying to restart the OpenVPN because it failed to ping, it sometimes covered up why it is failing because all they see is it keeps trying to restart.
This recovery script should be set to disable by default and should only be enabled manually after the container is running stable.
This approach should also take care of the server push overwriting the docker ping-restart issue.

What do you think?

**Comment by pkishino** [comment]
new PR merged #1805 that covers recovery etc.. is this one still needed/useful?

**Comment by RickyXwang** [comment]
Hi @pkishino, I took a quick look at #1805, it appears to me that the recovery is implemented as if it failed ping after certain tries it will `kill 1` which will restart the container (Correct me if I am wrong). Which is not what I was trying to do. What I wanted is a way to recover without restart the container first, and only when that failed we restart the container. So that it can avoid having to reload everything from the hard drive to the memory, as well as keeping a better record of the seeding status. In case the Tracker went down for a period of time, I would like to keep the transmission running if possible so when the Tracker went back up it has a consistent record.
I am still running my version of healthcheck in my container and it's working great so far. I got busy from work and haven't had time to follow up on the dev. So if someone wants to pick up my change they are welcome to do so. Or if you still want my change I may be able to merge it when I have more time (two months later maybe :<) If not you can just close this for good.

**Pull request closed without merging**
