### PR TITLE
Adding ProtonVPN Country Configs

### PR DESCRIPTION
**Pull request by kyleinprogress**
ProtonVPN recently added country configs that allow you to select a country and they will pick the fastest server. Easier than swapping configs.

### CODE REVIEW

**Comment by jyc66** [comment]
Will these configs pick p2p compatible server?

**Comment by kyleinprogress** [comment]
Yes. When you go to download the server configs from ProtonVPN, you have 3 options. One of them is "Country Configs" and both Sweden and Singapore are 100% P2P compatible.

Screen Shot 2019-04-22 at 11 59 05 AM

**Comment by jyc66** [comment]
I see, thanks for the explanation.

**Comment by haugene** [comment]
Looks good 👍 Thanks for contributing!

**Pull request merged**
