### PR TITLE
Changing back to Ubuntu base image

### PR DESCRIPTION
**Pull request by haugene**
## Breaking change
```txt
No. There should not be any breaking changes. People running custom scripts might get errors if they've based
the scripts on busybox versions of certain tools - but it should hopefully be a quick fix for those affected.
```

## Proposed change
```txt
I propose that we move back to basing the image on Ubuntu.
```
This relates to issues with the latest Transmission version: #1536 
And it relates issues on arm architecture with the latest alpine: #1726

But also other minor issues people have had with busybox tooling ++.
Long story short. Ubuntu is known and safe for many.

## Type of change
It is a bit of everything I guess. And hopefully nothing :smile: 

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to a this container)
- [x] Breaking change (fix/feature causing existing functionality to break)

## Additional information:

Some history. We started on ubuntu, and only for amd64 architecture. Then the community contributed to
adding an alpine image and it was tagged `alpine`, then we got `armhf` architecture support and we got
`latest-armhf` and `alpine-armhf` or what it was. And then arm64 showed up, and we got a lot of builds to maintain.
At this time we were more or lett maintaining a separate Dockerfile for each image tag.

Things have gotten easier. We have got the multiarch builds now, so we build armhf, arm64 and amd64 at the same time
and expose one image to pull. In return we've got better version tagging. That was more work previously (with so
many images) that it naturally happened more rarely.

Maintaining this image takes time. And it would make all our lives easier if it just worked. Some will want it to be very small, very fast, latest version of all libraries and base images +++. In this PR I'm suggesting to set a course for the future development. That it should be based on stable versions and that we'll take our time and grow with the LTS'es out there.

I think the majority of the users prefers this, and we can think about running an `edge` version of the image for those that want to contribute, test and be ahead of the curve.

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

### CODE REVIEW

**Comment by haugene** [comment]
FYI. I know this PR is not complete. I wanted to get a version up and running quickly on my localhost.
Have to add back privoxy that was introduced by @jay-to-the-dee in #1760. I'll rebase on top of that when I've got it working.

**Comment by jay-to-the-dee** [comment]
@haugene I'm sure we can get the build process running for Privoxy running fine on Ubuntu, may just need to find the package name equivalents is all. :)

Personally opinion is I really don't mind basing the image on Ubuntu. Tbh, torrenting needs a decent amount of disk space, Internet bandwidth and CPU power anyway, so no real imperative reason to insist on the docker image being Alpine or lightweight when the intended application itself usually isn't ;)

**Comment by haugene** [comment]
Glad to hear it, and thanks for the quick reply :+1: I don't think the difference for either users or maintainers will be big here. The point is rather that where it is different it leans towards stability and known territory.

About that... I was tempted and just added `privoxy` to the list of packages to install here. That would intsall version 3.0.28, and I see that your build from source gives us 3.0.29. But there was another benefit to building it that we could run  some new feature?

**Review by pkishino — APPROVED** [review]
Looks good to me and I agree that it will be a good move back to stability for all platforms

**Comment by haugene** [comment]
With my last commit Privoxy is working again within the container. It is just the version that is included in Ubuntu package repos but whether we should run a newer version might be another discussion.

I also cleaned up the startup script and changed killall for pkill as pkill is not in ubuntu by default.

What's the verdict here? Merge now and consider adding the custom build for newer version of privoxy later?
Would be nice to provide a fix for some of the alpine instabilities and have people test this out. I'm feeling that v4 of the image should go to master soon. But want to run it in dev for a little while at least to weed out the worst bugs.

**Comment by pkishino** [comment]
Yeah, I’m happy for the dev merge to go ahead.
Currently no fixed network at home due to move etc so won’t be able to test
until another week at least.

**Comment by jay-to-the-dee** [comment]
The HTTPS MITM support is still experimental/ alpha so much so, I don't use it at at all at present. It will however be a really great feature when it is ready and a bit more user friendly to use potentially (currently you have to make your own certificates)! 

So for now I would just use the Ubuntu package if it's that up to date (I didn't know it was that recent) ‐ especially if like you say, you're going for stability. The build script could be useful in the future though when those newer features come out that may or may not be enabled in the Ubuntu builds.

**Comment by haugene** [comment]
Definitely! Let us know when it's released. Anything that auto-generates certificates makes life so much easier. So let's see when they release it and how far it is from getting into the Ubuntu repos at that time.

**Comment by jay-to-the-dee** [comment]
@haugene Yeah will have to develop a script based on `easy-rsa` that does that and the appropriate config if Privoxy doesn't end up including a built in mechanism to do so.

**Pull request merged**
