### PR TITLE
Update ivpn configs

### PR DESCRIPTION
**Pull request by hongtron**
Adds config files for several new locations, and updates some settings in existing ones based on configs [downloaded from IVPN](https://www.ivpn.net/releases/config/ivpn-openvpn-config.zip) on 2/23/19 (e.g. [Canada.ovpn](https://github.com/haugene/docker-transmission-openvpn/pull/720/files#diff-4b104a56477b07c7b3eb4c283d994a41L15n)).

Generated by pulling the configs as linked above, and running `adjustConfigs.sh`. Also preserved the legacy filename format with spaces (the current versions use underscores in place of spaces) for backwards compatibility.

### CODE REVIEW

**Comment by haugene** [comment]
Thanks for helping out keeping the configs up to date 👍 This looks good to me.
Just one comment before I merge. I support the new naming conventions with underscore instead of space, and don't mind breaking backward compatibility on that small things.

So if you want we can change the naming, if not then I'll just merge :)

**Comment by hongtron** [comment]
Nice, I like the new naming too - I'll push the changes in the next day or two.

**Comment by hongtron** [comment]
@haugene should be ready to go now!

**Comment by haugene** [comment]
Great stuff, thanks for contributing! 👍

**Pull request merged**
