### PR TITLE
Add support for PIA nextgen VPN configuration(resolves #1334)

### LINKED ISSUE #1334: Update PIA configs to next gen servers
**Which provider?**
PIA

**Where are the configs?**
Should probably update to the next gen servers.

https://www.privateinternetaccess.com/helpdesk/news/posts/august-19th-2020-important-updated-server-changes-and-related-issues

### PR DESCRIPTION
**Pull request by zjorsie**
Resolves #1334 

Changed the pia/updateConfigs.sh script to create a folder 'nextgen' and put the nextgen scripts in that folder. Currently, port forwarding does not work on PIA's side (connections are refused when using nextgen config). 

Wrote a few lines in documentation explaining how to currently use the alternative configs (IP/TCP/strong security/nextgen).

Currently the following syntax can be used to use nonstandard tunnel configs can be used:
```
    OPENVPN_CONFIG=nextgen/France
```

Feels a bit hacky, but it works and is a general solution (possibly for other providers if they support multiple configs as well).

Furthermore, suppressed some output of the pia/updateConfigs.sh script. Reran the script and added the new ones:
`comp-lzo` changed to `compress` in PIA certificates.

Currently, port forwarding is not working with the nextgen config! This is due to the server (209.222.18.222:2000) that refuses connects when using 'nextgen' configs.  Probably since PIA is still migrating stuff. Warning added in the documentation.

### CODE REVIEW

**Comment by gdlx** [comment]
It would be nice to merge this quickly because there are a lot of issues recently on the old servers and they start recommending to migrate on nextgen ones: https://www.privateinternetaccess.com/helpdesk/news/posts/september-8-2020-important-updated-server-changes-and-related-issues

They also said 2 months ago that some nextgen locations have port forward enabled, so it worth a try: https://www.reddit.com/r/PrivateInternetAccess/comments/hoadt3/port_forwarding_in_new_locations_bug_or_a_feature/fxgpnii/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by zjorsie** [comment]
One problem came up. PIA does not (yet) allow port forwarding on their nextgen config outside of their PIA client. In the meantime, the current/old gen config works fine for now, so no hurry.

**Comment by fradav** [comment]
> One problem came up. PIA does not (yet) allow port forwarding on their nextgen config outside of their PIA client. In the meantime, the current/old gen config works fine for now, so no hurry.

Port forwarding still works on oldgen servers ? Which ones ?

**Comment by zjorsie** [comment]
I currently have Romania working.

**Comment by fradav** [comment]
You're right, just checked and its works, thanks for reporting!
Are there others ? Tried Switzerland, Sweden, DE Berlin, no port forwarding anymore

**Comment by gdlx** [comment]
Most of them didn't work for 2 days but it seems to be ok now.

**Comment by madbear2000** [comment]
Any word on when this is going to be merged.
None of the regions are working for me. 
It just sits there with
`Generating new client id for PIA
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 52
`

**Comment by chrislope** [comment]
It looks like as of yesterday (9/21) PIA has created scripts for the next gen servers to allow port forwarding: https://www.privateinternetaccess.com/helpdesk/kb/articles/next-generation-port-forwarding

**Comment by gdlx** [comment]
Sounds like next gen platform will have to be added as a new provider in the container...

**Comment by madbear2000** [comment]
This was posted on the 30th Sept 2020, which feels like it raises the priority of adding the like next gen platform to the container. 
https://www.privateinternetaccess.com/blog/private-internet-access-legacy-vpn-network-sunset-announcement-30-september/

**Comment by haugene** [comment]
As discussed. Closing this as #1398 supersedes it.

**Pull request closed without merging**
